print("<!DOCTYPE html>")
print("<html lang='en-us'>")
print("  <head>")
print("    <meta charset='utf-8'>")
print("    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>")
print("    <title>Unity WebGL Player | New Unity Project</title>")
print("    <link rel='shortcut icon' href='TemplateData/favicon.ico'>")
print("    <link rel='stylesheet' href='TemplateData/style.css'>")
print("    <script src='TemplateData/UnityProgress.js'></script>")
print("    <script src='Build/UnityLoader.js'></script>")
print("   <script>")
print("      var unityInstance = UnityLoader.instantiate('unityContainer', 'Build/UnityWorld.json', {onProgress: UnityProgress});")
print("    </script>")
print("  </head>")
print("  <body>")
print("    <div class='webgl-content'>")
print("     <div id='unityContainer' style='width: 960px; height: 600px'></div>")
print("      <div class='footer'>")
print("        <div class='webgl-logo'></div>")
print("        <div class='fullscreen' onclick='unityInstance.SetFullscreen(1)'></div>")
print("        <div class='title'>New Unity Project</div>")
print("      </div>")
print("    </div>")
print("  </body>")
print("</html>")
