#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<HTML>")
print("<head>")
print("<title>Home</title>")
print("<style>")
print("body {")
print("background-color: #0088cc;")
print("}")
print("<h1> {")
print("color: White;")
print("}")
print("</style>")
print("</head>")
print("<BODY>")
print("<style>")
print("BODY {")
print("  color: blue;")
print("}")

print("h1 {")
print("  color: White;")
print("}")
print("h3 {")
print("  color: red;")
print("}")
print("table, th, td {")
print("border: 1px solid White;")
print("border-collapse: collapse;")
print("}")
print("</style>")

print("<h1><hr><center>Home</center></hr></h1>")
print("<hr></hr>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<center><a href='shop0999847695.py'>Link</a><a href='about.py'> About</a> <a href='190882cari.py'>Cari Page </a> <a href='190882cari.py'> Cari Page</a></center>")
print("<table style='width:100%'>")
print("<tr>")
print("  <th>LINK</th>")
print("</tr>")
print("<tr>")
print("  <td><center><a href='not.py'>LINK</a></center></td>")
print("</tr>")
print("</table>")
print("<h6><center><hr>(c) copyright website <a href='discom.py'>Disconnect</a> </hr></center></h6>")
print("<hr></hr>")

print("</BODY>")
print("</HTML>")
