
#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Cari Page</title>")
print("<style>")
print("h1 {")
print("color: Blue;")
print("background-color: transparent;")
print("font-family: verdana;")
print("font-size: 72px;")
print("}")
print("body {")
print("background-color: lightblue;")
print("}")
print("p {")
print("color: blue;")
print("background-color: none;")
print("font-family: verdana;")
print("font-size: 48px;")
print("background-color: Green;")
print("}")
print("h6 {")
print("color: Blue;")
print("font-family: vredana;")
print("font-size: 24px;")
print("}")
print("a:link {")
print("background-color: transparent;")
print("text-decoration: none;")
print("}")
print("div {")
print("border: 1px black;")
print("width: 600px;")
print("height: 50px;")
print("overflow: scroll;")
print("}")
print("header.s {")
print("position: -webkit-sticky;")
print("position: sticky;")
print("top: 0;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<center>")
print("")
print("<h1><center>Welcome to Cari Page</center></h1>")
print("<hr></hr>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("")
print("<p>Welcome to Cari Page. To continue, Please click  a link.</p>")
print("<h6>Link: <a href='https://caripiano.music.blog'>Cari Piano    </a> <a href='mccari.py'>Minecraft</a> <a href='picari.py'> Piano </a></h6>")
print(">")
print("<h6>  </h6>")
print("<div onscroll>")
print("Copyright (c) By Cari Peng | and | Duo Peng")
print("2020 ")
print("ON scroll event")
print("Thank you so much !")
print("</div>")
print("<div>")
print("My Name Is Cari And Im Learning Piano")
print("I Want to teach Duo Piano")
print("But CAN NOT")
print("Wah wah wah :(")
print("end")
print("<header class='s'>")
print("<p>#by Car Peng June 29 2020 2020 - 6 - 29</p>")
print("<p>import os</p>")
print("<p>import time  </p>")
print("<p>import random     </p>")
print("<p>import turtle</p>")
print("<p>import ctypes</p>")
print("<p>from datetime import datetime</p>")
print("<p>from scapy.layers.dns import DNSStrField</p>")
print("<p>point=0</p>")
print("<p>fuelrobot=0</p>")
print("<p>coin=0</p>")
print("<p>reself = 5</p>")
print("<p></p>")
print("<p>now = datetime.now()</p>")
print("<p>current_time = now.strftime('%D %H:%M:%S')</p>")
print("<p>print(current_time)</p>")
print("<p>key=input('Press ENTER to continue...')</p>")
print("<p>print('lib/start/boot.dll')</p>")
print("<p>print('lib/boot/boot2.dll')</p>")
print("<p>print('system/boot/bootsys.dll')</p>")
print("<p>print('system/sysWOW64')</p>")
print("<p>print('var/crash/bootc.dll')</p>")
print("<p>print('system/info/boot.txt')</p>")
print("<p>trueflase = True</p>")
print("<p>for x in range(1000000):</p>")
print("<p>    print('>>>',end ='')</p>")
print("<p>    try:</p>")
print("<p>        a = input()</p>")
print("<p>        point+=0.001</p>")
print("<p>    except:</p>")
print("<p>        print('NO INPUT')</p>")
print("<p>    if str(a)=='cd perssonnal':</p>")
print("<p>        print('/perssonal',end='')</p>")
print("<p>        cd=input()</p>")
print("<p>        if str(cd)=='dir':</p>")
print("<p>            print('CARI PENG')</p>")
print("<p>        if str(cd)=='del':</p>")
print("<p>            print('are you sure want to delete 90 files to recycle bin? (y/n)')</p>")
print("<p>            delete = True</p>")
print("<p>            comfirmcd1=input()</p>")
print("<p>            if str(comfirmcd1)=='y':</p>")
print("<p>                #</p>")
print("<p>                for x in range(100):</p>")
print("<p>                    print('#',end='')</p>")
print("<p>                    time.sleep(0.1)</p>")
print("<p>                print('100%')</p>")
print("<p>                print('finish')</p>")
print("<p>    if str(a)=='ls':</p>")
print("<p>                #</p>")
print("<p>        print('2020/6/30 : Cari Birthday')</p>")
print("<p>        print('COVID-19')</p>")
print("<p>        print('Decoration Script')</p>")
print("<p>        print('System32')</p>")
print("<p>        print('System64')</p>")
print("<p>        print('2020/6/30 : apps')</p>")
print("<p>    if str(a) == '1':</p>")
print("<p>                #</p>")
print("<p>        print('''+str(a)+'''+'Command Not Found')</p>")
print("<p>    if str(a) == '2':</p>")
print("<p>        print(''' + str(a) + ''' + 'Command Not Found')</p>")
print("<p>    if str(a) == '3':</p>")
print("<p>        print(''' + str(a) + ''' + 'Command Not Found')</p>")
print("<p>    if str(a) == '4':</p>")
print("<p>        print( '''+str(a)+'''+'Command Not Found')</p>")
print("<p>    if str(a) =='5':</p>")
print("<p>                #</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='6':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='7':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='8':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='9':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='10':</p>")
print("<p>        print('''+1str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='wh1ere Cari Birthday':</p>")
print("<p>        print('Cari Birthday : C:/User/2473858/Cari Birthday.txt')</p>")
print("<p>    if str(a) == 'Say Hello':</p>")
print("<p>        print('Hello')</p>")
print("<p>    if str(a) == 'Apk Install Test':</p>")
print("<p>        print('scanning...')</p>")
print("<p>        time.sleep(15)</p>")
print("<p>        print('Scan Finish')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('installing...',end ='')</p>")
print("<p>        print('#',end = '')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('##########',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('##########',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('########',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Finish')</p>")
print("<p>        </p>")
print("<p>        </p>")
print("<p>    if str(a)=='update':</p>")
print("<p>        print('Scanning...')</p>")
print("<p>        time.sleep(15)</p>")
print("<p>        print('Scan Finish')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Updating...',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='apk install Cari Piano':</p>")
print("<p>        print('Scanning...')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('Scan Finish')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Installing',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(2)  </p>")
print("<p>    if str(a)=='apk install Python':</p>")
print("<p>        print('Installing Pypi...',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish installing Pypi')</p>")
print("<p>        time.sleep(0.9)</p>")
print("<p>        print('Installing Python...',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(2)   </p>")
print("<p>    if str(a)=='Password':</p>")
print("<p>        print('Enter Password In Input')</p>")
print("<p>    if str(a)=='Pc@cari9809':</p>")
print("<p>        print('KE25A Pc@caricari')   </p>")
print("<p>    if str(a)=='open.py':</p>")
print("<p>        print('Caculator.py or Multiplications.py')</p>")
print("<p>    if str(a)=='apk install Eclipse IDE':</p>")
print("<p>        print('Scanning')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('download package...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('installing...',end ='')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('scanning Packages...')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='download Eclipse IDE Packages':</p>")
print("<p>        print('Dowloaidng...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)  </p>")
print("<p>    if str(a)=='window10':</p>")
print("<p>        print('Dowloading System64...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading Decoration scripts...',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('downloading Apps...',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(5)  </p>")
print("<p>    if str(a)=='downgrade':</p>")
print("<p>        print('downloading system32...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading Decoration Scripts...',end='') </p>")
print("<p>        time.sleep(0.5)    </p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading apps...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('You Are Window 1.0')</p>")
print("<p>    if str(a)=='android':</p>")
print("<p>        print('Download Android files...')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('downloading scripts...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading Apps...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>    if str(a)=='scan-all':</p>")
print("<p>        print('Scanning...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        print('Scan Result :')</p>")
print("<p>        print('''</p>")
print("<p>              Cari Birthday.txt</p>")
print("<p>              Window</p>")
print("<p>              system32</p>")
print("<p>              system64</p>")
print("<p>              Apps</p>")
print("<p>              Decoration script</p>")
print("<p>                                ''')</p>")
print("<p>    if str(a)=='update-file':</p>")
print("<p>        print('Checking requirement...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('updating...',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Scanning...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(1)</p>")
print("<p>    if str(a)=='apk install Apache_tomcat':</p>")
print("<p>        print('Check requirement...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Downloading scripts...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Downloading files...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('installing...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='verifications':</p>")
print("<p>        print('verfications...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='del*':</p>")
print("<p>        delete = True</p>")
print("<p>        print('''</p>")
print("<p>              eclipse IDE</p>")
print("<p>              deleted</p>")
print("<p>              System32</p>")
print("<p>              Acces Denied</p>")
print("<p>              System64</p>")
print("<p>              Acces Denied</p>")
print("<p>              File</p>")
print("<p>              Deleted</p>")
print("<p>              Apps</p>")
print("<p>              Deleted</p>")
print("<p>              Cari Piano</p>")
print("<p>              deleted</p>")
print("<p>              Test</p>")
print("<p>              Deleted</p>")
print("<p>              Cari Birthday.txt</p>")
print("<p>              Deleted</p>")
print("<p>              Decoration Script</p>")
print("<p>              Acces Denied</p>")
print("<p>              Window</p>")
print("<p>              Acces Denied</p>")
print("<p>                                ''')</p>")
print("<p>    if str(a)=='Virus-scan':</p>")
print("<p>        </p>")
print("<p>        print('scanning...')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('scan result:')</p>")
print("<p>        print('''</p>")
print("<p>                good</p>")
print("<p>                    ''')</p>")
print("<p>    if str(a)=='restore':</p>")
print("<p>        try: </p>")
print("<p>            if delete == False:</p>")
print("<p>                print('No Item(s) to restore')</p>")
print("<p>            if delete == True:</p>")
print("<p>                print('Restore from recycle bin')</p>")
print("<p>                delete = False</p>")
print("<p>        except:</p>")
print("<p>            print('No item(s) to restore') </p>")
print("<p>            </p>")
print("<p>        </p>")
print("<p>    </p>")
print("<p>    if str(a)=='startup.sh':</p>")
print("<p>        print('''</p>")
print("<p>              Start Apache_tomcat9.0</p>")
print("<p>              use Catalina</p>")
print("<p>                                    ''')</p>")
print("<p>    if str(a)=='imformation-apache-tomcat9.0':</p>")
print("<p>        print('''</p>")
print("<p>              Apache Tomcat9.0</p>")
print("<p>              Publish on app/apache_tomcat9.0/webapps/user/</p>")
print("<p>              192.168.4.988:8080/                             ''')</p>")
print("<p>    if str(a)=='commands':</p>")
print("<p>        print('''</p>")
print("<p>              Say Hello</p>")
print("<p>              ls</p>")
print("<p>              Update</p>")
print("<p>              del*</p>")
print("<p>              apk install Apache_tomcat</p>")
print("<p>              apk install Eclipse IDE</p>")
print("<p>              apk install Python</p>")
print("<p>              apk install Cari Piano</p>")
print("<p>              Apk Install Test</p>")
print("<p>              imformation-apache-tomcat9.0</p>")
print("<p>              statup.sh</p>")
print("<p>              restore</p>")
print("<p>              verfications</p>")
print("<p>              Virus-scan</p>")
print("<p>              Password</p>")
print("<p>              other...                      ''')</p>")
print("<p>    if str(a)=='window':</p>")
print("<p>        print('check requirement...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Back to window...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>    if str(a)=='quit':</p>")
print("<p>        (0)</p>")
print("<p>    if str(a)=='apk install Java':</p>")
print("<p>        print('downloading files...')     </p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('installing...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='force-quit':</p>")
print("<p>        (1)  </p>")
print("<p>    if str(a)=='news':</p>")
print("<p>        print('''</p>")
print("<p>               COVID-19 -12 2019</p>")
print("<p>               Tremblement de terre - Mexico - 6 2020</p>")
print("<p>    </p>")
print("<p>    </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>               </p>")
print("<p>                                                        ''')</p>")
print("<p>    if str(a)=='cmd':</p>")
print("<p>        print('version : 1.20.31.0000')</p>")
print("<p>    if str(a)=='title':</p>")
print("<p>        print('Show Title : cmd')</p>")
print("<p>    if str(a)=='rename':</p>")
print("<p>        print('Rename ...:',end=' ')</p>")
print("<p>        i = input()</p>")
print("<p>        print('rename : '+str(i))</p>")
print("<p>    if str(a)=='Batchnew':</p>")
print("<p>        print('Username : ',end='')</p>")
print("<p>        login3=input()</p>")
print("<p>        if str(login3)=='caripeng30':</p>")
print("<p>            #</p>")
print("<p>            print('Password : ',end=' ')</p>")
print("<p>            password3=input()</p>")
print("<p>            if str(password3)=='Pccaricari':    </p>")
print("<p>                #</p>")
print("<p>                l = input()</p>")
print("<p>                print('Save name : ',end=' ')</p>")
print("<p>                c = input()</p>")
print("<p>                print('Saved : ' + str(c))</p>")
print("<p>    if str(a)=='run batch file':</p>")
print("<p>        if str(l)=='goto crash':</p>")
print("<p>            print('getting info at : GET.SYS.INFO.JAVA ')</p>")
print("<p>            print(':( Your PC ran into a problem')</p>")
print("<p>            print('getting info',end='')</p>")
print("<p>            time.sleep(2)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(2)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(2)</p>")
print("<p>            print('.')</p>")
print("<p>            time.sleep(6)</p>")
print("<p>            for batch in range(10000):</p>")
print("<p>                print(str(batch)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>                s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>                passlen = 26</p>")
print("<p>                error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>                time.sleep(0.001)</p>")
print("<p>                print (error)       </p>")
print("<p>            for batchc in range(0,101,1):</p>")
print("<p>                print(str(batchc)+'%'+'completed')</p>")
print("<p>                time.sleep(0.01)</p>")
print("<p>        time.sleep(6)</p>")
print("<p>            </p>")
print("<p>            </p>")
print("<p>    if str(a)=='class':</p>")
print("<p>        print('Username : ',end='')</p>")
print("<p>        q = input()</p>")
print("<p>        if str(q)=='caripeng30':</p>")
print("<p>            print('password : ',end='')</p>")
print("<p>            password4 = input()</p>")
print("<p>            if str(password4)=='Pccaricari':</p>")
print("<p>                #</p>")
print("<p>                print(type('class'))</p>")
print("<p>    if str(a)=='scripts': </p>")
print("<p>        print('username : ',end='--->>')</p>")
print("<p>        r = input()</p>")
print("<p>        if str(r)=='caripeng30':</p>")
print("<p>            print('Password : ',end=' ')</p>")
print("<p>            password10 = input()</p>")
print("<p>        if str(password10)=='Pccaricari':</p>")
print("<p>            print('''</p>")
print("<p>        import random</p>")
print("<p>import time</p>")
print("<p>from pdb import Restart</p>")
print("<p>for x in range(1000000):</p>")
print("<p>    number = '1234567890'</p>")
print("<p>    s = '1234567890'</p>")
print("<p>    passlen = 9</p>")
print("<p>    x =  ''.join(random.sample(s,passlen ))</p>")
print("<p>    s = '1234567890'</p>")
print("<p>    passlen = 9</p>")
print("<p>    i =  ''.join(random.sample(s,passlen ))</p>")
print("<p>    print('C:/users/Cari Peng/system>',end ='')</p>")
print("<p>    a = input()</p>")
print("<p>    if str(a)=='ls':</p>")
print("<p>        print('2020/6/30 : Cari Birthday')</p>")
print("<p>        print('COVID-19')</p>")
print("<p>        print('Window')</p>")
print("<p>        print('Decoration Script') </p>")
print("<p>        print('System32')</p>")
print("<p>        print('System64')</p>")
print("<p>        print('2020/6/30 : apps')</p>")
print("<p>    if str(a) == '1':</p>")
print("<p>        print('''+str(a)+'''+'Command Not Found')</p>")
print("<p>    if str(a) == '2':</p>")
print("<p>        print(''' + str(a) + ''' + 'Command Not Found')</p>")
print("<p>    if str(a) == '3':</p>")
print("<p>        print(''' + str(a) + ''' + 'Command Not Found')</p>")
print("<p>    if str(a) == '4':</p>")
print("<p>        print( '''+str(a)+'''+'Command Not Found')</p>")
print("<p>    if str(a) =='5':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='6':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='7':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='8':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='9':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='0':</p>")
print("<p>        print('''+str(a)+'''+'command Not Found')</p>")
print("<p>    if str(a) =='where Cari Birthday':</p>")
print("<p>        print('Cari Birthday : C:/User/2473858/Cari Birthday.txt')</p>")
print("<p>    if str(a) == 'Say Hello':</p>")
print("<p>        print('Hello')</p>")
print("<p>    if str(a) == 'Apk Install Test':</p>")
print("<p>        print('scanning...')</p>")
print("<p>        time.sleep(15)</p>")
print("<p>        print('Scan Finish')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('installing...',end ='')</p>")
print("<p>        print('#',end = '')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('##########',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('##########',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('########',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Finish')</p>")
print("<p>        </p>")
print("<p>        </p>")
print("<p>    if str(a)=='update':</p>")
print("<p>        print('Scanning...')</p>")
print("<p>        time.sleep(15)</p>")
print("<p>        print('Scan Finish')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Updating...',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='apk install Cari Piano':</p>")
print("<p>        print('Scanning...')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('Scan Finish')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Installing',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(2)  </p>")
print("<p>    if str(a)=='apk install Python':</p>")
print("<p>        print('Installing Pypi...',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish installing Pypi')</p>")
print("<p>        time.sleep(0.9)</p>")
print("<p>        print('Installing Python...',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(2)   </p>")
print("<p>    if str(a)=='Password':</p>")
print("<p>        print('Enter Password In Input')</p>")
print("<p>    if str(a)=='Pc@cari9809':</p>")
print("<p>        print('KE25A Pc@caricari')   </p>")
print("<p>    if str(a)=='open.py':</p>")
print("<p>        print('Caculator.py or Multiplications.py')</p>")
print("<p>    if str(a)=='apk install Eclipse IDE':</p>")
print("<p>        print('Scanning')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('download package...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('installing...',end ='')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>        print('#####',end ='')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('scanning Packages...')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='download Eclipse IDE Packages':</p>")
print("<p>        print('Dowloaidng...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)  </p>")
print("<p>    if str(a)=='window10':</p>")
print("<p>        print('Dowloading System64...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading Decoration scripts...',end ='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('downloading Apps...',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(5)  </p>")
print("<p>    if str(a)=='downgrade':</p>")
print("<p>        print('downloading system32...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading Decoration Scripts...',end='') </p>")
print("<p>        time.sleep(0.5)    </p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading apps...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('You Are Window 1.0')</p>")
print("<p>    if str(a)=='android':</p>")
print("<p>        print('Download Android files...')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('downloading scripts...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Downloading Apps...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>    if str(a)=='scan-all':</p>")
print("<p>        print('Scanning...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        print('Scan Result :')</p>")
print("<p>       </p>")
print("<p>    if str(a)=='update-file':</p>")
print("<p>        print('Checking requirement...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('updating...',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Scanning...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(1)</p>")
print("<p>    if str(a)=='apk install Apache_tomcat':</p>")
print("<p>        print('Check requirement...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Downloading scripts...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Downloading files...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('installing...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='verifications':</p>")
print("<p>        print('verfications...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='del*':</p>")
print("<p>                             </p>")
print("<p>    if str(a)=='Virus-scan':</p>")
print("<p>        </p>")
print("<p>        print('scanning...')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('scan result:')</p>")
print("<p>     </p>")
print("<p>    if str(a)=='restore':</p>")
print("<p>        print('Restore from recycle bin')</p>")
print("<p>    if str(a)=='startup.sh':</p>")
print("<p>    )</p>")
print("<p>    if str(a)=='imformation-apache-tomcat9.0':</p>")
print("<p> </p>")
print("<p>    if str(a)=='commands':</p>")
print("<p></p>")
print("<p>    if str(a)=='window':</p>")
print("<p>        print('check requirement...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Back to window...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('#####',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>    if str(a)=='quit':</p>")
print("<p>        (0)</p>")
print("<p>    if str(a)=='apk install Java':</p>")
print("<p>        print('downloading files...')     </p>")
print("<p>        time.sleep(5)</p>")
print("<p>        print('installing...',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('##########',end='')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        time.sleep(2)</p>")
print("<p>    if str(a)=='force-quit':</p>")
print("<p>        (1)  </p>")
print("<p>    if str(a)=='news':</p>")
print("<p>    if str(a)=='cmd':</p>")
print("<p>        print('version : 1.20.31.0000')</p>")
print("<p>    if str(a)=='title':</p>")
print("<p>        print('Show Title : cmd')</p>")
print("<p>    if str(a)=='rename':</p>")
print("<p>        print('Rename ...:',end=' ')</p>")
print("<p>        i = input()</p>")
print("<p>        print('rename : '+str(i))</p>")
print("<p>    if str(a)=='Batchnew':</p>")
print("<p>        l = input()</p>")
print("<p>        print('Save name : ',end=' ')</p>")
print("<p>        c = input()</p>")
print("<p>        print('Saved : ' + str(c))</p>")
print("<p>    if str(a)=='run batch file':</p>")
print("<p>        if str(l)=='goto crash':</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('Your PC has been crashed ')</p>")
print("<p>            print('@#$%^&*())(*&^%$#@!~!@#$%^&*()_)(*&^%$#@')</p>")
print("<p>            time.sleep(5)</p>")
print("<p>            (1)</p>")
print("<p>    if str(a)=='class':</p>")
print("<p>        print('Username : ',end='')</p>")
print("<p>        q = input()</p>")
print("<p>        if str(q)=='publicuser0999847695359':</p>")
print("<p>            print(type)</p>")
print("<p>        else:</p>")
print("<p>            Restart()</p>")
print("<p>    </p>")
print("<p>        </p>")
print("<p>       </p>")
print("<p>    </p>")
print("<p>                    </p>")
print("<p>      </p>")
print("<p>    </p>")
print("<p>    </p>")
print("<p></p>")
print("<p></p>")
print("<p></p>")
print("<p></p>")
print("<p>        </p>")
print("<p></p>")
print("<p>   </p>")
print("<p>    </p>")
print("<p>            </p>")
print("<p>                                                                                                                                                                      ''')</p>")
print("<p>    if str(a)=='personnal-imformation':</p>")
print("<p>        print('Username --->>',end =' ')</p>")
print("<p>        pf = input()   </p>")
print("<p>        if str(pf)=='caripeng30':</p>")
print("<p>            print('Password : ',end =' ')</p>")
print("<p>            password = input()</p>")
print("<p>            if str(password)=='Pccaricari':</p>")
print("<p>                </p>")
print("<p>                print('Cari's Birthday Is Comming !!!!! 2020 - 06 - 29')</p>")
print("<p>                print('I Like MINECRAFT 2020 - 06 - 29')</p>")
print("<p>                print('Line 830 to edit...')</p>")
print("<p>                print('Chicane 2020 - 06 - 30')</p>")
print("<p>                print('Birthday Cari 2020 - 06 - 30')</p>")
print("<p>                print('Life sucks 2020 - 06 - 30')</p>")
print("<p>            else:</p>")
print("<p>                print('Password incorrect')</p>")
print("<p>        else:</p>")
print("<p>            print('Username incorrect')</p>")
print("<p>    if str(a)=='family':</p>")
print("<p>        print('family code :',end='') </p>")
print("<p>        codefamily=input() </p>")
print("<p>        if str(codefamily)=='190882':</p>")
print("<p>            print('User',end='')</p>")
print("<p>            userfamily=input()</p>")
print("<p>            if str(userfamily)==('family190882'):</p>")
print("<p>                print('Door Number',end='')</p>")
print("<p>                passfamily=input()</p>")
print("<p>                if str(passfamily)==('DOOR'):</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('EDIT on line 861')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('Family Imformation')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('ACTIVITY : 2020 - 06 - 30 : Cari Birthday - FINISH - ')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('CALENDAR : 2020 - 07 - 01 : Canada Day -100%-')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('ACTIVITY : 2020 - 06 - 30 : Cake Cari Birthday - FINISH -')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('ACTIVITY : 2020 - 06 - 30 : activity Cari Birthday -CENCELED-')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('CARI : 2020 - 06 - 30 : SPECIAL Minecraft for 2 hours  - FINISHN -')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('ACTIVITY : 2020 - 06 - 30 PIANO ELECTRIC happy birthday - FINISH -')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('------------------------------')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('YING AND DUO DOOR NUMBER CODE : NP80H')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('CARI NUMBER CODE : KE25A')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('FAMILY CODE : 190882')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('-----------------------------')</p>")
print("<p>                    time.sleep(0.5)</p>")
print("<p>                    print('PIANO : very not good 2020 - 06 - 30')</p>")
print("<p>    if str(a)=='new_session':</p>")
print("<p>                print('BROKEN')</p>")
print("<p>                print('Your Name(complete)')</p>")
print("<p>                createusername=input()</p>")
print("<p>                print('Get Code : ')</p>")
print("<p>                s = '123456789012345678901234567890'</p>")
print("<p>                passlen = 30</p>")
print("<p>                passwordgenerator1 =  ''.join(random.sample(s,passlen ))</p>")
print("<p>                createusername2 = '{name:'+str(createusername)+'|code:'+str(passwordgenerator1)+'}'</p>")
print("<p>                print(str(createusername2))</p>")
print("<p>    if str(a)=='login':</p>")
print("<p>        #</p>")
print("<p>                    #</p>")
print("<p>        print('To enter a session, you need to create a session at the command : family-190882')</p>")
print("<p>        print('Login code : ',end='')</p>")
print("<p>        logingetcode=input()</p>")
print("<p>        try:</p>")
print("<p>            if str(logingetcode)==(createusername2):</p>")
print("<p>                #</p>")
print("<p>        #        #</p>")
print("<p>                        #</p>")
print("<p>                    print('Your session '+createusername2+' '+createusername)</p>")
print("<p>                    session=input() </p>")
print("<p>                    session12=input()</p>")
print("<p>                    session13=input()</p>")
print("<p>                    session14=input()</p>")
print("<p>                    session15=input()</p>")
print("<p>                    session16=input()</p>")
print("<p>            else:</p>")
print("<p>                        #</p>")
print("<p>                print('NO session') </p>")
print("<p>        except:</p>")
print("<p>            print(' getting info at GET.SYS.INFO.java')</p>")
print("<p>            time.sleep(6)</p>")
print("<p>            for log in range(10000):</p>")
print("<p>                print(str(log)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>                s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>                passlen = 26</p>")
print("<p>                error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>                time.sleep(0.001)</p>")
print("<p>                print (error)       </p>")
print("<p>            for logc in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.01)</p>")
print("<p>            print('100%')</p>")
print("<p>        #</p>")
print("<p>    if str(a)=='How To Create A New Session':</p>")
print("<p>        print('1.go to family-190882 command')</p>")
print("<p>        print('2. In Your Name (complete) write your name')</p>")
print("<p>        print('3. Get the code and Copy')</p>")
print("<p>        print('4. go to the command login and paste the code')</p>")
print("<p>        print('IF YOU D'ONT PASTE THE CODE, ERROR CRASH')</p>")
print("<p>    if str(a)=='login2':</p>")
print("<p>        print('Login Code : ')</p>")
print("<p>        logincode2=input()</p>")
print("<p>        try:</p>")
print("<p>            if str(logincode2)==(createusername2):</p>")
print("<p>                print(str(session)+''+str(session12)+''+str(session13)+''+str(session14)+''+str(session15)+''+str(session16),end='')</p>")
print("<p>                session2=input()</p>")
print("<p>                session22=input()</p>")
print("<p>                session23=input()</p>")
print("<p>        except:</p>")
print("<p>            print('getting info at : GET.SYS.INFO.JAVA ')</p>")
print("<p>            print(':( Your PC ran into a problem and need to restart :(')</p>")
print("<p>            print('getting info',end='')</p>")
print("<p>            time.sleep(2)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(2)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(2)</p>")
print("<p>            print('.')</p>")
print("<p>            time.sleep(6)</p>")
print("<p>            for login2ccc in range(101):</p>")
print("<p>                print(str(login2ccc)+'%')</p>")
print("<p>                time.sleep(0.1)</p>")
print("<p>        </p>")
print("<p>    </p>")
print("<p>            for login2c in range(10000):</p>")
print("<p>                print(str(login2c)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>                s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>                passlen = 26</p>")
print("<p>                error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>                time.sleep(0.001)</p>")
print("<p>                print (error)       </p>")
print("<p>            for login2cc in range(0,101,1):</p>")
print("<p>                print(str(login2cc)+'%'+'completed')</p>")
print("<p>                time.sleep(0.1)</p>")
print("<p>            time.sleep(6)</p>")
print("<p>    if str(a)=='name':</p>")
print("<p>        for name in range(1):</p>")
print("<p>            #</p>")
print("<p>            s = ('Duo','Cari','Ying')</p>")
print("<p>            passlen = 1</p>")
print("<p>            namegenerator1 =  ''.join(random.sample(s,passlen ))</p>")
print("<p>            print(namegenerator1)  </p>")
print("<p>    if str(a)=='!@#$%^&*()':</p>")
print("<p>        for i in range(10000):</p>")
print("<p>            print(str(i)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>            passlen = 26</p>")
print("<p>            error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>            time.sleep(0.001)</p>")
print("<p>            print (error)       </p>")
print("<p>        for v in range(0,101,1):</p>")
print("<p>            print(str(v)+'%'+'completed')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>    if str(a)=='SYS.INFO':</p>")
print("<p>        print('system code : ',end='')</p>")
print("<p>        s = '1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'</p>")
print("<p>        passlen = 10</p>")
print("<p>        SYSINFO =  ''.join(random.sample(s,passlen ))</p>")
print("<p>        print(SYSINFO) </p>")
print("<p>    if str(a)=='exit(0)':</p>")
print("<p>        print('do you want to exit? port 0(y/n)',end='')</p>")
print("<p>        exit0=input()</p>")
print("<p>        if str(exit0)=='y':</p>")
print("<p>            exit(0)        </p>")
print("<p>        else:</p>")
print("<p>            print('')</p>")
print("<p>    if str(a)=='exit(1)':</p>")
print("<p>        print('exit on port 1')</p>")
print("<p>        exit(1)</p>")
print("<p>    if str(a)=='internet':</p>")
print("<p>        print('URL--->>',end=' ')</p>")
print("<p>        url=input()</p>")
print("<p>    try:</p>")
print("<p>        if str(url)=='caripiano.music.blog':</p>")
print("<p>            print('exist')</p>")
print("<p>        elif str(url)=='caripeng.car.blog':</p>")
print("<p>            print('exist')</p>")
print("<p>        elif str(url)=='canada.ca':</p>")
print("<p>            print('exist')</p>")
print("<p>        else:</p>")
print("<p>            print('')</p>")
print("<p>    except:</p>")
print("<p>        point+=0.001</p>")
print("<p>    if str(a)=='find .':</p>")
print("<p>        print('find system')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('decoration')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('personnal')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('other')</p>")
print("<p>    if str(a)=='not_responding':</p>")
print("<p>        print('try to click the X (the turtle program)')</p>")
print("<p>        myTurtle = turtle.Turtle(shape='arrow')</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-10, 10)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-20,20)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-30, 30)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-40, 40)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-50, 50)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(10,-10)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(20, -20)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(30, -30)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(40, -40)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(50, -50)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(-50,-50)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-40, -40)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(-30, -30)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(-20, -20)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(-10, -10)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(50,50)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(40, 40)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.penup()</p>")
print("<p>        myTurtle.setposition(30, 30)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(20, 20)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        myTurtle.setposition(10, 10)</p>")
print("<p>        myTurtle.pendown()</p>")
print("<p>        myTurtle.circle(1)</p>")
print("<p>        turtle.done()</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('script need to terminate')</p>")
print("<p>        for n in range(10000):</p>")
print("<p>            print(str(n)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>            passlen = 26</p>")
print("<p>            error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>            time.sleep(0.001)</p>")
print("<p>            print (error)       </p>")
print("<p>        for w in range(0,101,1):</p>")
print("<p>            print(str(w)+'%'+'completed')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        time.sleep(6)</p>")
print("<p>        exit()</p>")
print("<p>    if str(a)=='kill sys.sys':</p>")
print("<p>        print('getting info at : GET.SYS.INFO.java')</p>")
print("<p>        time.sleep(6)</p>")
print("<p>        for b in range(10000):</p>")
print("<p>            print(str(b)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>            passlen = 26</p>")
print("<p>            error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>            time.sleep(0.001)</p>")
print("<p>            print (error)       </p>")
print("<p>        for z in range(0,101,1):</p>")
print("<p>            print(str(z)+'%'+'completed')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        time.sleep(6)</p>")
print("<p>    if str(a)=='open.all':</p>")
print("<p>        class CustomError(Exception):</p>")
print("<p>            pass</p>")
print("<p>        raise SystemError('To Many App Open crash32')</p>")
print("<p>    if str(a)=='kill service.localhost':</p>")
print("<p>        print('getting info at : GET.SYS.INFO.java')</p>")
print("<p>        time.sleep(6)</p>")
print("<p>        for kill in range(10000):</p>")
print("<p>            print(str(kill)+'ERROR:'+'file:'+'190882/family/system/code:',end='')</p>")
print("<p>                #</p>")
print("<p>            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'</p>")
print("<p>            passlen = 26</p>")
print("<p>            error =  ''.join(random.sample(s,passlen ))</p>")
print("<p>            time.sleep(0.001)</p>")
print("<p>            print (error)       </p>")
print("<p>        for crashkill in range(0,101,1):</p>")
print("<p>            print(str(crashkill)+'%'+'completed')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        time.sleep(6)</p>")
print("<p>    if str(a)=='del* sys.sys.all':</p>")
print("<p>        print('do you want to delete 9000 file (y/n)',end='')</p>")
print("<p>        delete = True</p>")
print("<p>        comfirmdel1=input()</p>")
print("<p>        if str(comfirmdel1)=='y':</p>")
print("<p>            for x in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>            print('100%')</p>")
print("<p>    if str(a)=='apk change sys.sys.update.upgrade.win10.all.*.fast.100':</p>")
print("<p>        print('comfirm (y/n)')</p>")
print("<p>        comfirmupgadewin101=input()</p>")
print("<p>        if str(comfirmupgadewin101)=='y':</p>")
print("<p>            for x in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.1)</p>")
print("<p>            print('100%')</p>")
print("<p>    if str(a)=='windows7.windows10.*':</p>")
print("<p>        print('comfirm (y/n)')</p>")
print("<p>        comfirmsystem7system10=input()</p>")
print("<p>        if str(comfirmsystem7system10)=='y':</p>")
print("<p>            for x in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>            print('100%')</p>")
print("<p>    if str(a)=='exe install Minecraft JE':</p>")
print("<p>        print('comfirm (y/n)')</p>")
print("<p>        comfirmminecraftexeinstallje=input()</p>")
print("<p>        if str(comfirmminecraftexeinstallje)=='y':</p>")
print("<p>            print('file...')</p>")
print("<p>            for x in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.1)</p>")
print("<p>            print('100%')</p>")
print("<p>            print('download...')</p>")
print("<p>            for x in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>            print('100%')</p>")
print("<p>    if str(a)=='run.eclipseIDE':</p>")
print("<p>        print('starting eclipse IDE...')</p>")
print("<p>        for runeclipseide in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        inputeclipseide=input()</p>")
print("<p>        if str(inputeclipseide)=='':</p>")
print("<p>            print('this is a test')</p>")
print("<p>    if str(a)=='vmware':</p>")
print("<p>        print('starting up...')</p>")
print("<p>        for vmware in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        print('command line can not startup in vmware. PLease start the command line on a real PC :(')</p>")
print("<p>        </p>")
print("<p>    if str(a)=='virtual.machine':</p>")
print("<p>        print('Please wait...')</p>")
print("<p>        for vm in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.3)</p>")
print("<p>        print('100%')</p>")
print("<p>        print('can not use virtual machine')</p>")
print("<p>    if str(a)=='pay':</p>")
print("<p>        print('___$')</p>")
print("<p>        pay=input()</p>")
print("<p>        print('To __')</p>")
print("<p>        payto=input()</p>")
print("<p>        print('****')</p>")
print("<p>        passpay=input()</p>")
print("<p>        if str(pay)=='':</p>")
print("<p>            print('please retry')</p>")
print("<p>        else:</p>")
print("<p>            #</p>")
print("<p>            print('pay'+':'+str(pay)+'$ '+ ' to '+str(payto))</p>")
print("<p>            for x in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.1)</p>")
print("<p>            print('100%')</p>")
print("<p>        if str(passpay)=='passpay':</p>")
print("<p>            print('approved')</p>")
print("<p>        else:</p>")
print("<p>            print('result :',end=' ')</p>")
print("<p>            print('CENCELED')</p>")
print("<p>    if str(a)=='shutdown.sys':</p>")
print("<p>        print('...')</p>")
print("<p>        for shutsys in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        exit(0)</p>")
print("<p>    if str(a)=='apk install Cari Piano2':</p>")
print("<p>        print('installing 999.9999999.MO')</p>")
print("<p>        for x in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(1)</p>")
print("<p>        print('100%')</p>")
print("<p>    if str(a)=='disconnect.net':</p>")
print("<p>        print('disconnected')</p>")
print("<p>    if str(a)=='connect.net':</p>")
print("<p>        print('connecting...')</p>")
print("<p>        for netconnect in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        print('finish')</p>")
print("<p>    if str(a)=='restart':</p>")
print("<p>        print('restarting...')</p>")
print("<p>        for restartsys1 in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('...')</p>")
print("<p>        time.sleep(10)</p>")
print("<p>        print('starting up...')</p>")
print("<p>        os.startfile('C:/Users/2473858/Desktop/1.mp3')</p>")
print("<p>        for x in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        print('connect to internet (net)')</p>")
print("<p>        for connectrestartsys1 in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        print('finish')</p>")
print("<p>        print('...')</p>")
print("<p>        time.sleep(3)        </p>")
print("<p>    if str(a)=='sleep':</p>")
print("<p>        print('...')</p>")
print("<p>        for sleepsys1 in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        print('100%')</p>")
print("<p>        exit()</p>")
print("<p>    if str(a)=='cd perssonnal/CARI PENG':</p>")
print("<p>        print('/perssonnal/CARI PENG',end='')</p>")
print("<p>        cdperssonnalCARIPENG=input()</p>")
print("<p>        if str(cdperssonnalCARIPENG)=='del':</p>")
print("<p>            print('comfirm (y/n)')</p>")
print("<p>            comfirmdelcdperssonnalCARIPENG=input()</p>")
print("<p>            if str(comfirmdelcdperssonnalCARIPENG)=='y':</p>")
print("<p>                delete = True</p>")
print("<p>                print('deleting...')</p>")
print("<p>                for x in range(100):</p>")
print("<p>                    print('#',end='')</p>")
print("<p>                    time.sleep(0.1)</p>")
print("<p>                print('100%')</p>")
print("<p>        if str(cdperssonnalCARIPENG)=='dir':</p>")
print("<p>            print('HTML')</p>")
print("<p>            print('PYTHON')</p>")
print("<p>            print('CSS')</p>")
print("<p>            print('PHP')</p>")
print("<p>            print('??? 2020 -06')</p>")
print("<p>            print('COMPRESSED 2020 -06')</p>")
print("<p>            print('OTHER 2020 - 06')</p>")
print("<p>    if str(a)=='cd perssonnal/CARI PENG/HTML':</p>")
print("<p>        print('perssonnal/CARI PENG/HTML')</p>")
print("<p>        inputperssonnalCARIPENGhtml=input()</p>")
print("<p>        if str(inputperssonnalCARIPENGhtml)=='del':</p>")
print("<p>            print('comfirm (y/n)')</p>")
print("<p>            comfirmdelcdperssonnalCARIPENGHTML=input()</p>")
print("<p>            if str(comfirmdelcdperssonnalCARIPENGHTML)=='y':</p>")
print("<p>                delete = True</p>")
print("<p>                print('deleting...')</p>")
print("<p>                for comfirmdelcdperssonnalCARIPENGHTML2 in range(100):</p>")
print("<p>                    print('#',end='')</p>")
print("<p>                    time.sleep(0.1)</p>")
print("<p>                print('100%')</p>")
print("<p>        if str(inputperssonnalCARIPENGhtml)=='dir':</p>")
print("<p>            print('my_table.html')</p>")
print("<p>            print('progress.html')</p>")
print("<p>            print('multiplications.html')</p>")
print("<p>            print('index.html')</p>")
print("<p>            print('index.html')</p>")
print("<p>            print('script.html')</p>")
print("<p>            print('...')</p>")
print("<p>    if str(a)=='note-script':</p>")
print("<p>        print('username:')</p>")
print("<p>        usernamenotescript=input()</p>")
print("<p>        if str(usernamenotescript)=='caripeng30':</p>")
print("<p>            print('password:')</p>")
print("<p>            passwordnotescript=input()</p>")
print("<p>            if str(passwordnotescript)=='pass.scr.note':</p>")
print("<p>                print('edit on line 1406')</p>")
print("<p>                print('finish CD explorer')</p>")
print("<p>                print('make for - in range progress')</p>")
print("<p>    if str(a)=='bug':</p>")
print("<p>        print('1 bug')</p>")
print("<p>                   </p>")
print("<p>    if str(a)=='copy.sys.sys.exe':</p>")
print("<p>        print('Finish')</p>")
print("<p>    if str(a)=='run copy.sys.sys.exe':</p>")
print("<p>        class CustomException(Exception):</p>")
print("<p>            pass</p>")
print("<p>        raise CustomException('can not run system')</p>")
print("<p>    if str(a)=='r.pi':</p>")
print("<p>        class CustomException(Exception):</p>")
print("<p>            pass</p>")
print("<p>        raise SystemError(' I D'ont Like Piano')</p>")
print("<p>    if str(a)=='reset.pc':</p>")
print("<p>        print('comfirm (y/n)')</p>")
print("<p>        comfirmresetpc1=input()</p>")
print("<p>        if str(comfirmresetpc1)=='y':</p>")
print("<p>            print('deleting file...')</p>")
print("<p>            for deletefilerestepc in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>            print('100%')</p>")
print("<p>            print('reinstalling System...')</p>")
print("<p>            for reinstallingwindowsresetpc1 in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(1)</p>")
print("<p>            print('100%')</p>")
print("<p>            print('setup is checking your computer',end='')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('.')</p>")
print("<p>            for setupcheckingpc in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>            print('100%')</p>")
print("<p>            print('Please Wait...')</p>")
print("<p>            for pleasewait in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.3)</p>")
print("<p>            print('FINISH')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('loading',end='')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('.',end='')</p>")
print("<p>            time.sleep(3)</p>")
print("<p>            print('.')</p>")
print("<p>            time.sleep(10)</p>")
print("<p>    if str(a)=='ERRORexceptionPID19283345':</p>")
print("<p>        class CustomException(Exception):</p>")
print("<p>            pass</p>")
print("<p>        raise SystemError('SUCCESS:ERRORexceptionPID19283345')</p>")
print("<p>    if str(a)=='__END__':</p>")
print("<p>        print('Terminate Computer')</p>")
print("<p>        class CustomException(Exception):</p>")
print("<p>            pass</p>")
print("<p>        raise SystemError('Computer BROKEN Please buy a new computer')</p>")
print("<p>    if str(a)=='add.doc':</p>")
print("<p>        os.startfile('C:/Users/2473858/Desktop//APPLICATION ERROR.exe')</p>")
print("<p>        time.sleep(5)</p>")
print("<p>    if str(a)=='start':</p>")
print("<p>        os.startfile('C:/Users/2473858/Documents/Python//cmd.py')</p>")
print("<p>    if str(a)=='Chrome':</p>")
print("<p>        os.startfile('C:/Program Files (x86)/Google/Chrome/Application//chrome.exe')</p>")
print("<p>    if str(a)=='explorer':</p>")
print("<p>        os.startfile('C:/Users/2473858')</p>")
print("<p>    if str(a)=='errorx10':</p>")
print("<p>        for errorxdix in range(10):</p>")
print("<p>            os.startfile('C:/Users/2473858/Desktop/APPLICATION ERROR.exe')</p>")
print("<p>    if str(a)=='file':</p>")
print("<p>        print('file')</p>")
print("<p>        fileinput=input()</p>")
print("<p>        try:</p>")
print("<p>            os.startfile(fileinput)</p>")
print("<p>        except:</p>")
print("<p>            print('can not find the file')   </p>")
print("<p>    if str(a)=='web':</p>")
print("<p>        print('https://',end='')</p>")
print("<p>        web=input()</p>")
print("<p>        os.startfile('https://'+(web))</p>")
print("<p>    if str(a)=='word':</p>")
print("<p>            #</p>")
print("<p>        os.startfile('C:/windows/write')</p>")
print("<p>    if str(a)=='microsoft.VSTUDIO':</p>")
print("<p>        print('downloading packages...')</p>")
print("<p>        for downpack_mirosoft in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        print('installing packages...')</p>")
print("<p>        print('microsoft.debugger.VSTUDIO')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.policy...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.editor...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack1...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack80...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack100...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.runpack0...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.debugger_pack90...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.editor_pack800...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.script.pack60...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSSTUDIO.copy_paste_pack90...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack19')</p>")
print("<p>        for microsoft_VSTUDIO_pack in range(262):</p>")
print("<p>            print('microsoft.VSTUDIO.pack'+str(microsoft_VSTUDIO_pack)+'...')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        for end_PROGRESS_microsoft_VSTUDIO in range(100):</p>")
print("<p>            print('=',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('FINISH')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>    if str(a)=='install.UNITY3D.exe':</p>")
print("<p>        for prepa_unity_3d_install in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('installing...')</p>")
print("<p>        print('downloading packages...')</p>")
print("<p>        for downpack_mirosoft in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        print('installing packages...')</p>")
print("<p>        print('microsoft.debugger.VSTUDIO')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.policy...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.editor...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack1...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack80...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack100...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.runpack0...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.debugger_pack90...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.editor_pack800...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.script.pack60...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSSTUDIO.copy_paste_pack90...')</p>")
print("<p>        time.sleep(0.5)</p>")
print("<p>        print('microsoft.VSTUDIO.pack19')</p>")
print("<p>        for microsoft_VSTUDIO_pack in range(262):</p>")
print("<p>            print('microsoft.VSTUDIO.pack'+str(microsoft_VSTUDIO_pack)+'...')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('finish')</p>")
print("<p>        for end_PROGRESS_microsoft_VSTUDIO in range(100):</p>")
print("<p>            print('=',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('FINISH')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>    if str(a)=='systeminfo':</p>")
print("<p>        print('loading...')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('loading system info...')</p>")
print("<p>        for loading_pack_systeminfo in range(263):</p>")
print("<p>            </p>")
print("<p>            print('loading pack'+str(loading_pack_systeminfo)+'...')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>            print('''</p>")
print("<p>            Host Name:                 CARI-PC</p>")
print("<p>OS Name:                   system 10 Family</p>")
print("<p>OS Version:                10.0.18363 N/A Build 18363</p>")
print("<p>OS Manufacturer:           Cari Peng </p>")
print("<p>OS Configuration:          Standalone Workstation</p>")
print("<p>OS Build Type:             Multiprocessor Free</p>")
print("<p>Registered Owner:          Cari Peng</p>")
print("<p>Registered Organization:</p>")
print("<p>Product ID:                098-776-55443</p>")
print("<p>Original Install Date:     4/1/2020, 12:03:24 AM</p>")
print("<p>System Boot Time:          7/9/2020, 12:03:31 PM</p>")
print("<p>System Manufacturer:       190882_FAMILY</p>")
print("<p>System Model:              190882KE25ANP80H</p>")
print("<p>System Type:               x86-based PC</p>")
print("<p>Processor(s):              10 Processor(s) Installed.</p>")
print("<p>                           [01]: SYSTEM64 Family 18 Model 1 Stepping 0 AuthenticAMD ~1500 Mhz</p>")
print("<p>BIOS Version:              SYSTEM 1.12</p>")
print("<p>perssonal Directory:       190882/family/perssonal</p>")
print("<p>System Directory:          190882/family/system</p>")
print("<p>Boot Device:               \Device\HarddiskVolume2</p>")
print("<p>System Locale:             en-ca;English (Canada)</p>")
print("<p>Input Locale:              en-us;English (United States)</p>")
print("<p>Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)</p>")
print("<p>Total Physical Memory:     5,611 MB</p>")
print("<p>Available Physical Memory: 2,756 MB</p>")
print("<p>Virtual Memory: Max Size:  11,243 MB</p>")
print("<p>Virtual Memory: Available: 8,222 MB</p>")
print("<p>Virtual Memory: In Use:    3,021 MB</p>")
print("<p>Domain:                    190882_FAMILY_SYSTEM</p>")
print("<p>Logon Server:              \CARI-PC</p>")
print("<p>Hotfix(s):                 12 Hotfix(s) Installed.</p>")
print("<p>                           [01]: KB4552931</p>")
print("<p>                           [02]: KB4513661</p>")
print("<p>                           [03]: KB4516115</p>")
print("<p>                           [04]: KB4517245</p>")
print("<p>                           [05]: KB4528759</p>")
print("<p>                           [06]: KB4537759</p>")
print("<p>                           [07]: KB4541338</p>")
print("<p>                           [08]: KB4552152</p>")
print("<p>                           [09]: KB4559309</p>")
print("<p>                           [10]: KB4560959</p>")
print("<p>                           [11]: KB4561600</p>")
print("<p>                           [12]: KB4560960</p>")
print("<p>Network Card(s):           2 NIC(s) Installed.</p>")
print("<p>                           [01]: Qualcomm Atheros AR5B97 Wireless Network Adapter</p>")
print("<p>                                 Connection Name: Wi-Fi</p>")
print("<p>                                 DHCP Enabled:    Yes</p>")
print("<p>                                 DHCP Server:     192.168.3.1</p>")
print("<p>                                 IP address(es)</p>")
print("<p>                                 [01]: 192.168.3.129</p>")
print("<p>                           [02]: Broadcom NetLink (TM) Gigabit Ethernet</p>")
print("<p>                                 Connection Name: Local Area Connection</p>")
print("<p>                                 Status:          Hardware not present</p>")
print("<p>Hyper-V Requirements:      VM Monitor Mode Extensions: Yes</p>")
print("<p>                           Virtualization Enabled In Firmware: Yes</p>")
print("<p>                           Second Level Address Translation: Yes</p>")
print("<p>                           Data Execution Prevention Available: Yes</p>")
print("<p>                                                                                           ''')</p>")
print("<p>            print('can not print all')</p>")
print("<p>    if str(a)=='download Minecraft':</p>")
print("<p>        print('downloading...')</p>")
print("<p>        for down_file_java_file in range(1001):</p>")
print("<p>            print('packages.mojang.MCJE_'+str(down_file_java_file) + '.java '+str(down_file_java_file)+' of 1000')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        for mojang_installing_MC in range(100):</p>")
print("<p>            s = 'abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'</p>")
print("<p>            passlen = 100</p>")
print("<p>            mojang_install_MC2 =  ''.join(random.sample(s,passlen ))</p>")
print("<p>            print ('downloading : '+str(mojang_install_MC2)+' type : folder'+' Publisher : Mojang ')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('Download MCpack.MCPE...')</p>")
print("<p>        time.sleep(0.7)</p>")
print("<p>        print('download Run.MCPE.INst.setup')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        print('Completing Downloads... Please wait...')</p>")
print("<p>        time.sleep(6)</p>")
print("<p>        print('FINISH')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('Preparing to running script...')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        for downinst_MCJE_FOR_IN_RANGE in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.3)</p>")
print("<p>        print('FINISH')</p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('Please Wait...')</p>")
print("<p>    if str(a)=='VIRUS.SCAN_SYS':</p>")
print("<p>        comfirm_scan_virus_key=input('Press ENTER to continue... Else use quit to quit')</p>")
print("<p>        if comfirm_scan_virus_key=='':</p>")
print("<p>            print('scanning...')</p>")
print("<p>            for scan_virus_sys in range(100):</p>")
print("<p>                print('#',end='')</p>")
print("<p>                time.sleep(0.1)</p>")
print("<p>            print('100%')</p>")
print("<p>            print('NO VIRUS FOOUND!')</p>")
print("<p>            </p>")
print("<p>        </p>")
print("<p>        time.sleep(3)</p>")
print("<p>        print('FINISH')</p>")
print("<p>    if str(a)=='Cari':</p>")
print("<p>        print('H',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('e',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('l',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('l',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('o',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print(',',end='')</p>")
print("<p>        print(' ',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('m',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('y',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print(' ',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('n',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('a',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('m',end='')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('e')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('is Cari.')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        print('')</p>")
print("<p>        time.sleep(0.2)</p>")
print("<p>        for mynameno in range(200):</p>")
print("<p>            print('-',end='')</p>")
print("<p>            time.sleep(0.01)</p>")
print("<p>        print('-')</p>")
print("<p>    if str(a)=='Install Virus':</p>")
print("<p>        trueflase = False</p>")
print("<p>        for progvirusinst in range(100):</p>")
print("<p>            print('#',end='')</p>")
print("<p>            time.sleep(0.1)</p>")
print("<p>        print('100%')</p>")
print("<p>        print('Finish')</p>")
print("<p>    if str(a)=='CHEAT:_update_truefalse:True':</p>")
print("<p>        trueflase = True</p>")
print("<p>    if str(a)=='CHEAT:_update_truefalse:False':</p>")
print("<p>        trueflase = False</p>")
print("<p>    if str(a)=='True False':</p>")
print("<p>        if trueflase == True:</p>")
print("<p>            print('No Virus True')</p>")
print("<p>        else:</p>")
print("<p>            print('VIRUS False')</p>")
print("<p>    if str(a)=='CPL':</p>")
print("<p>        print('Point + 1')</p>")
print("<p>        point+=1</p>")
print("<p>    if str(a)=='CPP':</p>")
print("<p>        print('point:'+str(point))</p>")
print("<p>    if str(a)=='CPPclear':</p>")
print("<p>        print('Clearing ALL')</p>")
print("<p>        point=0.000000000000000000000000001</p>")
print("<p>    if str(a)=='time':</p>")
print("<p>        for time1 in range(1):</p>")
print("<p>            #</p>")
print("<p>            now = datetime.now()</p>")
print("<p>            current_time = now.strftime('%D %H:%M:%S')</p>")
print("<p>            print(current_time)</p>")
print("<p>            time.sleep(1)</p>")
print("<p>    if str(a)=='Save.note':</p>")
print("<p>        print('Save')</p>")
print("<p>        save_note=input()</p>")
print("<p>        save_note1=save_note</p>")
print("<p>    if str(a)=='open save.note':</p>")
print("<p>        try:</p>")
print("<p>            print(save_note1)</p>")
print("<p>        except:</p>")
print("<p>            print('Save.note do not exist')</p>")
print("<p>    if str(a)=='CHEAT:_get.permCP19:True':</p>")
print("<p>        permCP19=True</p>")
print("<p>        print('Updated')</p>")
print("<p>    if str(a)=='abcp19':</p>")
print("<p>        try:</p>")
print("<p>            if permCP19 == True:</p>")
print("<p>                print('Nothing Test')</p>")
print("<p>            else:</p>")
print("<p>                print('please get permCP19')</p>")
print("<p>        except:</p>")
print("<p>            print('Please Get permCP19')</p>")
print("<p>    if str(a)=='CHEAT:_del.permCP19:False':</p>")
print("<p>        print('Updated')</p>")
print("<p>    if str(a)=='Restart.sys':</p>")
print("<p>        print('restarting...')</p>")
print("<p>        os.startfile('C:/Users/2473858/Documents/Python//cmd.py')</p>")
print("<p>        time.sleep(0.1)</p>")
print("<p>        exit(0)</p>")
print("<p>        permCP19=False</p>")
print("<p>    def CAPSLOCK_STATE():</p>")
print("<p>        hllDll = ctypes.WinDLL ('User32.dll')</p>")
print("<p>        VK_CAPITAL = 0x14</p>")
print("<p>        return hllDll.GetKeyState(VK_CAPITAL)</p>")
print("<p></p>")
print("<p>    CAPSLOCK = CAPSLOCK_STATE()</p>")
print("<p>    if ((CAPSLOCK) & 0xffff) != 0:</p>")
print("<p>        print('</p>")
print("<p> CAPS LOCK IS ON</p>")
print("<p>')</p>")
print("<p>    import json</p>")
print("<p>    if str(a)=='saving json file':</p>")
print("<p>        nameJson1 = input('Username')</p>")
print("<p>        passwordJson1 = input('Password')</p>")
print("<p>        letters = (str(nameJson1)+str(passwordJson1))</p>")
print("<p></p>")
print("<p>        numbers = []</p>")
print("<p>        for letter in letters:</p>")
print("<p>            for JsonTestP in  range(1):</p>")
print("<p>                #</p>")
print("<p>                number = ord(letter) - 96</p>")
print("<p>                numbers.append(number)</p>")
print("<p></p>")
print("<p>        print(numbers)</p>")
print("<p>        jsonfile1 = {</p>")
print("<p>        'info':(numbers)</p>")
print("<p>        }</p>")
print("<p></p>")
print("<p>        with open('INFO'+(nameJson1), 'w') as json_file:</p>")
print("<p>            json.dump(jsonfile1, json_file)</p>")
print("<p>    if str(a)=='un-install sys':</p>")
print("<p>           </p>")
print("<p>        </p>")
print("<p>        </p>")
print("<p>        try:</p>")
print("<p>            os.remove('C:/Users/2473858/Desktop//INFO')</p>")
print("<p>            os.remove('C:/Users/2473858/Desktop//INFO2system')</p>")
print("<p>        except:</p>")
print("<p>            print('ERROR')</p>")
print("<p>    if str(a)=='version':</p>")
print("<p>        version = 19</p>")
print("<p>        versionb = 15.19</p>")
print("<p>        print(version//versionb//1915.1915++version//versionb)</p>")
print("<p>    if str(a)=='main.sh':</p>")
print("<p>        print('starting main.sh...')</p>")
print("<p>        main = input('wating for fuel...')</p>")
print("<p>        if str(main)=='st':</p>")
print("<p>            if fuelrobot==0:</p>")
print("<p>                print('no perm to start')</p>")
print("<p>            else:</p>")
print("<p>                fuelrobot-=1</p>")
print("<p>                print('starting up...')</p>")
print("<p>                for main0 in range(10):</p>")
print("<p>                    for main1 in range(1, 50):</p>")
print("<p>                        for main2 in range(1, main1):</p>")
print("<p>                            print('#',end='')</p>")
print("<p>                            time.sleep(0.001)</p>")
print("<p>                        print(' ')</p>")
print("<p>            print('FINISH')</p>")
print("<p>    if str(a)=='perm+':</p>")
print("<p>        print('checking...')</p>")
print("<p>        if coin==0:</p>")
print("<p>            print('no coin')</p>")
print("<p>        else:</p>")
print("<p>            print('add perm !')</p>")
print("<p>            fuelrobot+=2</p>")
print("<p>            coin-=2</p>")
print("<p>    if str(a)=='coin':</p>")
print("<p>        print(coin)</p>")
print("<p>    if str(a)=='perm':</p>")
print("<p>        print(fuelrobot)</p>")
print("<p>    if str(a)=='coin+f':</p>")
print("<p>        print('Cheacking...')</p>")
print("<p>        if fuelrobot==0:</p>")
print("<p>            print('No perm to add.')</p>")
print("<p>        else:</p>")
print("<p>            coin+=1</p>")
print("<p>    if str(a)=='coin+self':</p>")
print("<p>        print('Checking...')</p>")
print("<p>        if reself==0:</p>")
print("<p>            print('Bad Chance :(')</p>")
print("<p>        else:</p>")
print("<p>            coin+=10</p>")
print("<p>            reself-=1</p>")
print("<p>    if str(a)=='self':</p>")
print("<p>        print(reself)</p>")
print("<p>    if str(a)=='trianglesPYex':</p>")
print("<p>        print('Checking...')</p>")
print("<p>        if fuelrobot==0:</p>")
print("<p>            print('No Perm')</p>")
print("<p>        else:</p>")
print("<p>            fuelrobot-=1</p>")
print("<p>            print('''</p>")
print("<p>        for i in range(1, 10):</p>")
print("<p>            for j in range(1, i):</p>")
print("<p>                print('*')</p>")
print("<p>            print(' ')</p>")
print("<p>    result :</p>")
print("<p>    </p>")
print("<p>    *</p>")
print("<p>    **</p>")
print("<p>    ***</p>")
print("<p>    ****</p>")
print("<p>    *****</p>")
print("<p>    ******</p>")
print("<p>    *******</p>")
print("<p>    ********</p>")
print("<p>    *********</p>")
print("<p>    **********</p>")
print("<p>                                                        ''')</p>")
print("<p>    if str(a)=='vim system/info/boot.txt':</p>")
print("<p>        print('Boot imformation : Boot from Hard Drive')</p>")
print("<p>    if str(a)=='vim var/vrash/bootc.dll':</p>")
print("<p>        print('acess denied')</p>")
print("<p>    if str(a)=='cd system/sysWOW64':</p>")
print("<p>        print('acess denied')</p>")
print("<p>    if str(a)=='vim system/boot/bootsys.dll':</p>")
print("<p>        print('Acess denied')</p>")
print("<p>    if str(a)=='vim lin/start/boot.dll':</p>")
print("<p>        print('acess denied')</p>")
print("<p>    if str(a)=='exit':</p>")
print("<p>        exit(0)</p>")
print("<p>    if str(a)=='re':</p>")
print("<p>        os.startfile('C:/Users/2473858/Documents/Python/cmd.py')</p>")
print("<p>        exit(0)</p>")
print("<p>    if str(a)=='coin.':</p>")
print("<p>        coina=input()</p>")
print("<p>        if str(coina)=='transform-perm+':</p>")
print("<p>            print('Verifing...')</p>")
print("<p>            if coin==0:</p>")
print("<p>                print('No coin')</p>")
print("<p>                coin+=1</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>                reself-=1</p>")
print("<p>                time.sleep(0.5)</p>")
print("<p>                fuelrobot+=1</p>")
print("<p>                coin-=1</p>")
print("<p>                print('Finish')</p>")
print("<p>            else:</p>")
print("<p>                fuelrobot+=1</p>")
print("<p>                coin-=1</p>")
print("<p>                print('Finish')</p>")
print("<p>        if str(coina)=='coin-self+':</p>")
print("<p>            print('...')</p>")
print("<p>            if coin==0:</p>")
print("<p>                print('No action needed')</p>")
print("<p>            else:</p>")
print("<p>                coin-=1</p>")
print("<p>                reself+=1</p>")
print("<p>                print('Finish')</p>")
print("<p>        if str(coina)=='transform-coin+':</p>")
print("<p>            if reself==0:</p>")
print("<p>                print('No Self')</p>")
print("<p>            else:</p>")
print("<p>                reself-=5</p>")
print("<p>                coin+=50</p>")
print("</header>")

print("</div>")
print("</center>")
print("</body>")
print("</html>")

