#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Editable PYTHON cmd.py</title>")
print("</head>")
print("<body>")
print("<h4>editable, but not saved</h4>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<form>")
print("<textarea name='cmd' cols=1 rows=1>")
print("My Name Is Cari Accept Cookies Policy")
print("By Cari Peng | and | Duo Peng")
print("Cari Peng work : Make DISPLAY")
print("Duo Peng work : MAKE DATABASE AND OTHER")
print("-*-*-*-*-")
print("The Peng Group")
print("editable, unsaved")
print("Go to 192.168.3.115:8080/gateway/cgi-bin/about.py To Learn More.")
print("Subscribe to my Youtube Channel")
print("Subscribe to Cari | Piano ")
print("go to Caripiano.music.blog")
print("Subscribe to My Blog !")
print("Subscribe to Ying | Zhan !")
print("yingzhan.home.blog")
print("WILL NOT SAVED DATA IN YOUR COMPUTER")
print("After Yes, For now NO")
print("BY TEXTAREA IN HTML display")
print("By Cari Peng Peng Group")
print("(c) Copyright Cari Peng (The Peng Group)")
print("</textarea>")
print("</form>")
print("</body>")
print("</html>")

