#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Page Title</title>")
print("<style>")
print("body {")
print("background-color: #0088cc;")
print("}")
print("h1 {")
print("color: White;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<h1><center><hr>Please Comfirm</hr></center></h1>")
print("<hr></hr>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<table style='width:100%'>")
print("<tr>")
print("  <th><a href='login.py'>Comfirm</a>")
print("</tr>")
print("<tr>")
print("  <th><a href='0999847695359.py'>Cencel</a>")
print(" </tr>")
print("</table>")
print("</body>")
print("</html>")

