#!/usr/bin/python3
print ("Content-type:text/html\n\n")
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("<!--")
print("")
print("Template 2082 Pure Mix")
print("")
print("http://www.tooplate.com/view/2082-pure-mix")
print("")
print("-->")
print("	<meta charset='utf-8'>")
print("	<meta http-equiv='X-UA-Compatible' content='IE=Edge'>")
print("	<meta name='viewport' content='width=device-width, initial-scale=1'>")
print("	<meta name='keywords' content=''>")
print("	<meta name='description' content=''>")
print("")
print("	<!-- Site title")
print("   ================================================== -->")
print("	<title>eCurtains - Home</title>")
print("")
print("	<!-- Bootstrap CSS")
print("   ================================================== -->")
print("	<link rel='stylesheet' href='css/bootstrap.min.css'>")
print("")
print("	<!-- Animate CSS")
print("   ================================================== -->")
print("	<link rel='stylesheet' href='css/animate.min.css'>")
print("")
print("	<!-- Font Icons CSS")
print("   ================================================== -->")
print("	<link rel='stylesheet' href='css/font-awesome.min.css'>")
print("	<link rel='stylesheet' href='css/ionicons.min.css'>")
print("")
print("	<!-- Main CSS")
print("   ================================================== -->")
print("	<link rel='stylesheet' href='css/style.css'>")
print("")
print("	<!-- Google web font ")
print("   ================================================== -->	")
print("  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,300' rel='stylesheet' type='text/css'>")
print("	")
print("</head>")
print("<body>")
print("")
print("")
print("<!-- Preloader section")
print("================================================== -->")
print("<div class='preloader'>")
print("")
print("	<div class='sk-spinner sk-spinner-pulse'></div>")
print("")
print("</div>")
print("")
print("")
print("<!-- Navigation section")
print("================================================== -->")
print("<div class='nav-container'>")
print("   <nav class='nav-inner transparent'>")
print("")
print("      <div class='navbar'>")
print("         <div class='container'>")
print("            <div class='row'>")
print("")
print("              <div class='brand'>")
print("                <a href='index.html'>eCurtains</a>")
print("              </div>")
print("")
print("              <div class='navicon'>")
print("                <div class='menu-container'>")
print("")
print("                  <div class='circle dark inline'>")
print("                    <i class='icon ion-navicon'></i>")
print("                  </div>")
print("")
print("                  <div class='list-menu'>")
print("                    <i class='icon ion-close-round close-iframe'></i>")
print("                    <div class='intro-inner'>")
print("                      <ul id='nav-menu'>")
print("                        <li><a href='index.html'>Home</a></li>")
print("                        <li><a href='about.html'>About</a></li>")
print("                        <li><a href='blog.html'>Blog</a></li>")
print("                        <li><a href='contact.html'>Contact</a></li>")
print("                        <li><a href='account.html'>Account</a></li>")
print("                      </ul>")
print("                    </div>")
print("                  </div>")
print("")
print("                </div>")
print("		<div class='sign-in'>")
print("                    <a href='signIn.py'>Sign In</a>")
print("                </div>")
print("")
print("              </div>")
print("")
print("            </div>")
print("         </div>")
print("      </div>")
print("")
print("   </nav>")
print("</div>")
print("")
print("")
print("<!-- Header section")
print("================================================== -->")
print("<section id='header' class='header-one'>")
print("	<div class='container'>")
print("		<div class='row'>")
print("")
print("			<div class='col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8'>")
print("          <div class='header-thumb'>")
print("              <h1 class='wow fadeIn' data-wow-delay='1.6s'>eCurtains: Curtain Expert</h1>")
print("              <h3 class='wow fadeInUp' data-wow-delay='1.9s'>All kinds of Curtains included</h3>")
print("          </div>")
print("			</div>")
print("")
print("		</div>")
print("	</div>		")
print("</section>")
print("")
print("")
print("<!-- Portfolio section")
print("================================================== -->")
print("<section id='portfolio'>")
print("   <div class='container'>")
print("      <div class='row'>")
print("")
print("         <div class='col-md-12 col-sm-12'>")
print("            ")
print("               <!-- iso section -->")
print("               <div class='iso-section wow fadeInUp' data-wow-delay='2.6s'>")
print("")
print("                  <ul class='filter-wrapper clearfix'>")
print("                           <li><a href='#' data-filter='*' class='selected opc-main-bg'>All</a></li>")
print("                           <li><a href='#' class='opc-main-bg' data-filter='.graphic'>Graphic</a></li>")
print("                           <li><a href='#' class='opc-main-bg' data-filter='.template'>Web template</a></li>")
print("                           <li><a href='#' class='opc-main-bg' data-filter='.photoshop'>Photoshop</a></li>")
print("                        <li><a href='#' class='opc-main-bg' data-filter='.branding'>Branding</a></li>")
print("                        </ul>")
print("")
print("                        <!-- iso box section -->")
print("                        <div class='iso-box-section wow fadeInUp' data-wow-delay='1s'>")
print("                           <div class='iso-box-wrapper col4-iso-box'>")
print("")
print("                              <div class='iso-box photoshop branding col-md-4 col-sm-6'>")
print("                                 <div class='portfolio-thumb'>")
print("                                    <img src='images/portfolio-img1.jpg' class='img-responsive' alt='Portfolio'>")
print("                                       <div class='portfolio-overlay'>")
print("                                          <div class='portfolio-item'>")
print("                                                <a href='single-project.html'><i class='fa fa-link'></i></a>")
print("                                                <h2>Project One</h2>")
print("                                             </div>")
print("                                       </div>")
print("                                 </div>")
print("                              </div>")
print("")
print("                              <div class='iso-box graphic template col-md-4 col-sm-6'>")
print("                                 <div class='portfolio-thumb'>")
print("                                    <img src='images/portfolio-img2.jpg' class='img-responsive' alt='Portfolio'>")
print("                                       <div class='portfolio-overlay'>")
print("                                          <div class='portfolio-item'>")
print("                                                <a href='single-project.html'><i class='fa fa-link'></i></a>")
print("                                                <h2>Project Two</h2>")
print("                                             </div>")
print("                                       </div>")
print("                                 </div>")
print("                              </div>")
print("")
print("                              <div class='iso-box template graphic col-md-4 col-sm-6'>")
print("                                 <div class='portfolio-thumb'>")
print("                                    <img src='images/portfolio-img3.jpg' class='img-responsive' alt='Portfolio'>")
print("                                       <div class='portfolio-overlay'>")
print("                                          <div class='portfolio-item'>")
print("                                                <a href='single-project.html'><i class='fa fa-link'></i></a>")
print("                                                <h2>Project Three</h2>")
print("                                             </div>")
print("                                       </div>")
print("                                 </div>")
print("                              </div>")
print("")
print("                              <div class='iso-box graphic template col-md-4 col-sm-6'>")
print("                                 <div class='portfolio-thumb'>")
print("                                    <img src='images/portfolio-img4.jpg' class='img-responsive' alt='Portfolio'>")
print("                                       <div class='portfolio-overlay'>")
print("                                          <div class='portfolio-item'>")
print("                                                <a href='single-project.html'><i class='fa fa-link'></i></a>")
print("                                                <h2>Project Four</h2>")
print("                                             </div>")
print("                                       </div>")
print("                                 </div>")
print("                              </div>")
print("")
print("                              <div class='iso-box photoshop branding col-md-4 col-sm-6'>")
print("                                 <div class='portfolio-thumb'>")
print("                                    <img src='images/portfolio-img5.jpg' class='img-responsive' alt='Portfolio'>")
print("                                       <div class='portfolio-overlay'>")
print("                                          <div class='portfolio-item'>")
print("                                                <a href='single-project.html'><i class='fa fa-link'></i></a>")
print("                                                <h2>Project Five</h2>")
print("                                             </div>")
print("                                       </div>")
print("                                 </div>")
print("                              </div>")
print("")
print("                              <div class='iso-box graphic branding col-md-4 col-sm-6'>")
print("                                 <div class='portfolio-thumb'>")
print("                                    <img src='images/portfolio-img6.jpg' class='img-responsive' alt='Portfolio'>")
print("                                       <div class='portfolio-overlay'>")
print("                                          <div class='portfolio-item'>")
print("                                                <a href='single-project.html'><i class='fa fa-link'></i></a>")
print("                                                <h2>Project Six</h2>")
print("                                             </div>")
print("                                       </div>")
print("                                 </div>")
print("                              </div>")
print("")
print("                            </div>")
print("                        </div>")
print("")
print("               </div>")
print("")
print("         </div>")
print("")
print("      </div>")
print("   </div>")
print("</section>")
print("")
print("<!-- Footer section")
print("================================================== -->")
print("<footer>")
print("	<div class='container'>")
print("		<div class='row'>")
print("")
print("			<div class='col-md-12 col-sm-12'>")
print("				<p class='wow fadeInUp'  data-wow-delay='0.3s'>Copyright © 2020 ecurtain - Designed by Cari/Duo</p>")
print("				<ul class='social-icon wow fadeInUp'  data-wow-delay='0.6s'>")
print("					<li><a href='#' class='fa fa-facebook'></a></li>")
print("					<li><a href='#' class='fa fa-twitter'></a></li>")
print("					<li><a href='#' class='fa fa-dribbble'></a></li>")
print("					<li><a href='#' class='fa fa-behance'></a></li>")
print("					<li><a href='#' class='fa fa-google-plus'></a></li>")
print("				</ul>")
print("			</div>")
print("			")
print("		</div>")
print("	</div>")
print("</footer>")
print("")
print("")
print("<!-- Javascript ")
print("================================================== -->")
print("<script src='js/jquery.js'></script>")
print("<script src='js/bootstrap.min.js'></script>")
print("<script src='js/isotope.js'></script>")
print("<script src='js/imagesloaded.min.js'></script>")
print("<script src='js/wow.min.js'></script>")
print("<script src='js/custom.js'></script>")
print("")
print("</body>")
print("</html>")
print("")
