
#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Page Title</title>")
print("<style>")
print("textarea {")
print("background-color: black;")
print("font-family: courier;")
print("color: white;")
print("font-size:13px;")
print("width: 1355px;")
print("height: 600px;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<div>")
print("<form>")
print("<textarea  name='404notfoundtomcat9ubuntupenggroup' cols=1 rows=1 placeholder = 'Enter your code'>")
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<meta name='viewport' content='width=device-width, initial-scale=1'>")
print("<style>")
print(".loader {")
print("  border: 16px solid #f3f3f3;")
print("  border-radius: 50%;")
print("  border-top: 16px solid #3498db;")
print("  width: 120px;")
print("  height: 120px;")
print("  -webkit-animation: spin 2s linear infinite; /* Safari */")
print("  animation: spin 2s linear infinite;")
print("}")
print("")
print("/* Safari */")
print("@-webkit-keyframes spin {")
print("  0% { -webkit-transform: rotate(0deg); }")
print("  100% { -webkit-transform: rotate(360deg); }")
print("}")
print("")
print("@keyframes spin {")
print("  0% { transform: rotate(0deg); }")
print("  100% { transform: rotate(360deg); }")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("")
print("<h2>How To Create A Loader</h2>")
print("")
print("<div class='loader'></div>")
print("")
print("</body>")
print("</html>")
print("")
print("</textarea>")
print("</body>")
print("</html>")

