#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>My_table.html</title>")
print("<style>")
print("table {")
print("  font-family:Courier;")
print("  border-collapse:collapse;")
print("  width: 100%;")
print("}")
print("")
print("td, th {")
print("  border: 1px solid #000000;")
print("  text-align: center;")
print("  padding: 8px;")
print("}")
print("")
print("tr:nth-child(even) {")
print("  background-color: #e6e6ff;")
print("}")
print("td:nth-child(even) {")
print("  background-color: #ccccff;")
print("}")
print("")
print("</style>")
print("</head>")
print("<body>")
print("")
print("<table>")
print("  ")
print("  <tr>")
print("    <th><strong>X</strong></th>")
print("    <th>1</th>")
print("    <th>2</th>")
print("    <th>3</th>")
print("    <th>4</th>")
print("    <th>5</th>")
print("    <th>6</th>")
print("    <th>7</th>")
print("    <th>8</th>")
print("    <th>9</th>")
print("    <th>10</th>")
print("  </tr>")
print("  <tr>")
print("    <th>1</th>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td> ")
print("    <td><input type='number' name='number'/></td>")
print("  </tr>")
print("  <tr>")
print("    <th>2</th>")
print("     <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td>")
print("    <td><input type='number' name='number'/></td> ")
print("    <td><input type='number' name='number'/></td>")
print("  </tr>")
print("  <tr>")
print("    <th>3</th>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td>")
print("  </tr>")
print("  <tr>")
print("    <th>4</th>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td>")
print("  </tr>")
print("  <tr>")
print("    <th>5</th>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td>")
print("  </tr>")
print("  ")
print("  <tr>")
print("    <th>6</th>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td>")
print("    <td><input type='number' name='number'/> </td> ")
print("    <td><input type='number' name='number'/> </td>")
print("    </tr>")
print("    ")
print("    <tr>")
print("      <th>7</th>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td>")
print("      <td><input type='number' name='number'/> </td> ")
print("      <td><input type='number' name='number'/> </td>")
print("      </tr>")
print("      ")
print("      <tr>")
print("        <th>8</th>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td> ")
print("        <td><input type='number' name='number'/> </td>")
print("        <td><input type='number' name='number'/> </td>")
print("        </tr>")
print("        ")
print("        <tr>")
print("          <th>9</th>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td>")
print("          <td><input type='number' name='number'/> </td> ")
print("          <td><input type='number' name='number'/> </td>")
print("          </tr>")
print("          ")
print("          <tr>")
print("            <th>10</th>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td>")
print("             <td><input type='number' name='number'/> </td> ")
print("             <td><input type='number' name='number'/> </td>")
print("            </tr>")
print("</table>")
print("<p>Finish<input type='checkbox' name='finish'/><p>")
print("")
print("</body>")
print("</html>")
