#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Piano</title>")
print("<style>")
print("h1 {")
print("font-family: tahoma, arial;")
print("font-size: 48px;")
print("}")
print("body {")
print("background-color: lightblue;")
print("font-family: courier;")
print("}")
print("view {")
print("font-family: impact;")
print("font-size: 16px;")
print("color: Blue;")
print("}")
print("de {")
print("font-family: impact;")
print("}")
print("</style>")
print("</head>")
print("<center>")
print("<body>")
print("<h1><de>Piano</de></h1>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<p>Im learning <de>SUZUKI.</de></p>")
print("<h4><view>View : </view>My Dream Life</h4>")
print("<p><a href='https://musescore.com/user/32839396/scores/6039028'>https://musescore.com/user/32839396/scores/6039028</a></p>")
print("<h4><view>View</view> : My Musescore Account</h4>")
print("<p><a href='https://musescore.com/user/32839396'>https://musescore.com/user/32839396</a></p>")
print("<p>Copyright (c) Cari Peng | Cari Piano | Visit <a href='https://caripiano.music.blog'>Cari Piano</a></p>")
print("</body>")
print("</center>")
print("</html>")

