#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Report a problem</title> ")
print("<style>")
print("body {")
print("background-color: lightblue;")
print("}")
print("a:link {")
print("color:blue;")
print("background-color: transparent;")
print("text-decoration: under-line;")
print("font-family: verdana;")
print("font-size: 12px;")
print("}")
print("h1 {")
print("font-family: verdana;")
print("font-size: 72;")
print("color: white;")
print("}")
print("table, tr, td {")
print("border: 1px solid black;")
print("}")
print("th {")
print("color: white;")
print("font-size: 25px;")
print("}")
print("th, td {")
print("padding: 15px;")
print("color: black;")
print("}")
print("hr {")
print("color: black;")
print("}")
print("input {")
print("color: gray;")
print("font-size: 15px;")
print("font-family: verdana;")
print("}")
print("th {")
print("color: white;")
print("font-size: 36px;")
print("font-family: verdana;")
print("</style>")
print("</head>")
print("<body>")
print("<hr>")
print("<h1><center>Report a problem</center></h1>")
print("<a href='about.py'>About</a>")
print("<a href='mailto:caripeng30@gmail.com'>Contact us</a>")
print("<hr style='height:5px;border-width:100;color:white;background-color:black'>")
print("")
print("<table style='width:100%'>")
print("<form method='POST' action='contactus.py'>")
print("<tr>")
print("  <th colspan='2'>report a roblem</th>")
print("</tr>")
print("<tr>")
print("  <td>Enter Your Name : </td>")
print("  <td><input type=text value='Enter your Name' required></td>")
print("</tr>")
print("<tr>")
print("  <td>Enter more information : </td>")
print("  <td><input type=text value='Add some description' required></td>")
print("</tr>")
print("<tr>")
print("  <td> or add some File : </td>")
print("  <td><input type='file'></td>")
print("</tr>")
print("<tr>")
print("  <td colspan='2'><center><input type='submit' value='send'></center></td>")
print("</tr>")
print("</table>")
print("</body>")
print("</html>")

