#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Page Title</title>")
print("<style>")
print("textarea {")
print("background-color: black;")
print("font-family: courier;")
print("color: white;")
print("font-size:13px;")
print("width: 1355px;")
print("height: 600px;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<div>")
print("<form>")
print("<textarea  name='404notfoundtomcat9ubuntupenggroup' cols=1 rows=1 placeholder = 'Enter your code'>")
print("#by Car Peng June 29 2020 2020 - 6 - 29")
print("import os")
print("import time  ")
print("import random     ")
print("import turtle")
print("import ctypes")
print("from datetime import datetime")
print("from scapy.layers.dns import DNSStrField")
print("point=0")
print("fuelrobot=0")
print("coin=0")
print("reself = 5")
print("")
print("now = datetime.now()")
print("current_time = now.strftime('%D %H:%M:%S')")
print("print(current_time)")
print("key=input('Press ENTER to continue...')")
print("print('lib/start/boot.dll')")
print("print('lib/boot/boot2.dll')")
print("print('system/boot/bootsys.dll')")
print("print('system/sysWOW64')")
print("print('var/crash/bootc.dll')")
print("print('system/info/boot.txt')")
print("trueflase = True")
print("for x in range(1000000):")
print("    print('>>>',end ='')")
print("    try:")
print("        a = input()")
print("        point+=0.001")
print("    except:")
print("        print('NO INPUT')")
print("    if str(a)=='cd perssonnal':")
print("        print('/perssonal',end='')")
print("        cd=input()")
print("        if str(cd)=='dir':")
print("            print('CARI PENG')")
print("        if str(cd)=='del':")
print("            print('are you sure want to delete 90 files to recycle bin? (y/n)')")
print("            delete = True")
print("            comfirmcd1=input()")
print("            if str(comfirmcd1)=='y':")
print("                #")
print("                for x in range(100):")
print("                    print('#',end='')")
print("                    time.sleep(0.1)")
print("                print('100%')")
print("                print('finish')")
print("    if str(a)=='ls':")
print("                #")
print("        print('2020/6/30 : Cari Birthday')")
print("        print('COVID-19')")
print("        print('Decoration Script')")
print("        print('System32')")
print("        print('System64')")
print("        print('2020/6/30 : apps')")
print("    if str(a) == '1':")
print("                #")
print("        print('''+str(a)+'''+'Command Not Found')")
print("    if str(a) == '2':")
print("        print(''' + str(a) + ''' + 'Command Not Found')")
print("    if str(a) == '3':")
print("        print(''' + str(a) + ''' + 'Command Not Found')")
print("    if str(a) == '4':")
print("        print( '''+str(a)+'''+'Command Not Found')")
print("    if str(a) =='5':")
print("                #")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='6':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='7':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='8':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='9':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='0':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='where Cari Birthday':")
print("        print('Cari Birthday : C:/User/2473858/Cari Birthday.txt')")
print("    if str(a) == 'Say Hello':")
print("        print('Hello')")
print("    if str(a) == 'Apk Install Test':")
print("        print('scanning...')")
print("        time.sleep(15)")
print("        print('Scan Finish')")
print("        time.sleep(3)")
print("        print('installing...',end ='')")
print("        print('#',end = '')")
print("        time.sleep(3)")
print("        print('##########',end ='')")
print("        time.sleep(3)")
print("        print('##########',end ='')")
print("        time.sleep(3)")
print("        print('########',end ='')")
print("        time.sleep(3)")
print("        print('Finish')")
print("        ")
print("        ")
print("    if str(a)=='update':")
print("        print('Scanning...')")
print("        time.sleep(15)")
print("        print('Scan Finish')")
print("        time.sleep(0.5)")
print("        print('Updating...',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='apk install Cari Piano':")
print("        print('Scanning...')")
print("        time.sleep(10)")
print("        print('Scan Finish')")
print("        time.sleep(0.5)")
print("        print('Installing',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(2)  ")
print("    if str(a)=='apk install Python':")
print("        print('Installing Pypi...',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####')")
print("        time.sleep(0.5)")
print("        print('finish installing Pypi')")
print("        time.sleep(0.9)")
print("        print('Installing Python...',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(2)   ")
print("    if str(a)=='Password':")
print("        print('Enter Password In Input')")
print("    if str(a)=='Pc@cari9809':")
print("        print('KE25A Pc@caricari')   ")
print("    if str(a)=='open.py':")
print("        print('Caculator.py or Multiplications.py')")
print("    if str(a)=='apk install Eclipse IDE':")
print("        print('Scanning')")
print("        time.sleep(5)")
print("        print('download package...')")
print("        time.sleep(3)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('installing...',end ='')")
print("        time.sleep(2)")
print("        print('#####',end ='')")
print("        time.sleep(2)")
print("        print('#####',end ='')")
print("        time.sleep(2)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('scanning Packages...')")
print("        time.sleep(5)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='download Eclipse IDE Packages':")
print("        print('Dowloaidng...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(2)  ")
print("    if str(a)=='window10':")
print("        print('Dowloading System64...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('Downloading Decoration scripts...',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('downloading Apps...',end='')")
print("        time.sleep(0.1)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(5)  ")
print("    if str(a)=='downgrade':")
print("        print('downloading system32...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('Downloading Decoration Scripts...',end='') ")
print("        time.sleep(0.5)    ")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('Downloading apps...',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(3)")
print("        print('##########',end='')")
print("        time.sleep(0.5)")
print("        print('finish')")
print("        time.sleep(0.5)")
print("        print('You Are Window 1.0')")
print("    if str(a)=='android':")
print("        print('Download Android files...')")
print("        time.sleep(5)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('downloading scripts...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('Downloading Apps...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("    if str(a)=='scan-all':")
print("        print('Scanning...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        print('Scan Result :')")
print("        print('''")
print("              Cari Birthday.txt")
print("              Window")
print("              system32")
print("              system64")
print("              Apps")
print("              Decoration script")
print("                                ''')")
print("    if str(a)=='update-file':")
print("        print('Checking requirement...')")
print("        time.sleep(0.5)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('updating...',end='')")
print("        time.sleep(0.1)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('Scanning...')")
print("        time.sleep(3)")
print("        print('Finish')")
print("        time.sleep(1)")
print("    if str(a)=='apk install Apache_tomcat':")
print("        print('Check requirement...')")
print("        time.sleep(3)")
print("        print('Downloading scripts...')")
print("        time.sleep(3)")
print("        print('Downloading files...')")
print("        time.sleep(0.5)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('installing...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='verifications':")
print("        print('verfications...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(2)")
print("    if str(a)=='del*':")
print("        delete = True")
print("        print('''")
print("              eclipse IDE")
print("              deleted")
print("              System32")
print("              Acces Denied")
print("              System64")
print("              Acces Denied")
print("              File")
print("              Deleted")
print("              Apps")
print("              Deleted")
print("              Cari Piano")
print("              deleted")
print("              Test")
print("              Deleted")
print("              Cari Birthday.txt")
print("              Deleted")
print("              Decoration Script")
print("              Acces Denied")
print("              Window")
print("              Acces Denied")
print("                                ''')")
print("    if str(a)=='Virus-scan':")
print("        ")
print("        print('scanning...')")
print("        time.sleep(10)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('scan result:')")
print("        print('''")
print("                good")
print("                    ''')")
print("    if str(a)=='restore':")
print("        try: ")
print("            if delete == False:")
print("                print('No Item(s) to restore')")
print("            if delete == True:")
print("                print('Restore from recycle bin')")
print("                delete = False")
print("        except:")
print("            print('No item(s) to restore') ")
print("            ")
print("        ")
print("    ")
print("    if str(a)=='startup.sh':")
print("        print('''")
print("              Start Apache_tomcat9.0")
print("              use Catalina")
print("                                    ''')")
print("    if str(a)=='imformation-apache-tomcat9.0':")
print("        print('''")
print("              Apache Tomcat9.0")
print("              Publish on app/apache_tomcat9.0/webapps/user/")
print("              192.168.4.988:8080/                             ''')")
print("    if str(a)=='commands':")
print("        print('''")
print("              Say Hello")
print("              ls")
print("              Update")
print("              del*")
print("              apk install Apache_tomcat")
print("              apk install Eclipse IDE")
print("              apk install Python")
print("              apk install Cari Piano")
print("              Apk Install Test")
print("              imformation-apache-tomcat9.0")
print("              statup.sh")
print("              restore")
print("              verfications")
print("              Virus-scan")
print("              Password")
print("              other...                      ''')")
print("    if str(a)=='window':")
print("        print('check requirement...')")
print("        time.sleep(3)")
print("        print('Back to window...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(5)")
print("    if str(a)=='quit':")
print("        (0)")
print("    if str(a)=='apk install Java':")
print("        print('downloading files...')     ")
print("        time.sleep(5)")
print("        print('installing...',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='force-quit':")
print("        (1)  ")
print("    if str(a)=='news':")
print("        print('''")
print("               COVID-19 -12 2019")
print("               Tremblement de terre - Mexico - 6 2020")
print("    ")
print("    ")
print("               ")
print("               ")
print("               ")
print("               ")
print("               ")
print("               ")
print("               ")
print("               ")
print("               ")
print("                                                        ''')")
print("    if str(a)=='cmd':")
print("        print('version : 1.20.31.0000')")
print("    if str(a)=='title':")
print("        print('Show Title : cmd')")
print("    if str(a)=='rename':")
print("        print('Rename ...:',end=' ')")
print("        i = input()")
print("        print('rename : '+str(i))")
print("    if str(a)=='Batchnew':")
print("        print('Username : ',end='')")
print("        login3=input()")
print("        if str(login3)=='caripeng30':")
print("            #")
print("            print('Password : ',end=' ')")
print("            password3=input()")
print("            if str(password3)=='Pccaricari':    ")
print("                #")
print("                l = input()")
print("                print('Save name : ',end=' ')")
print("                c = input()")
print("                print('Saved : ' + str(c))")
print("    if str(a)=='run batch file':")
print("        if str(l)=='goto crash':")
print("            print('getting info at : GET.SYS.INFO.JAVA ')")
print("            print(':( Your PC ran into a problem')")
print("            print('getting info',end='')")
print("            time.sleep(2)")
print("            print('.',end='')")
print("            time.sleep(2)")
print("            print('.',end='')")
print("            time.sleep(2)")
print("            print('.')")
print("            time.sleep(6)")
print("            for batch in range(10000):")
print("                print(str(batch)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("                s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("                passlen = 26")
print("                error =  ''.join(random.sample(s,passlen ))")
print("                time.sleep(0.001)")
print("                print (error)       ")
print("            for batchc in range(0,101,1):")
print("                print(str(batchc)+'%'+'completed')")
print("                time.sleep(0.01)")
print("        time.sleep(6)")
print("            ")
print("            ")
print("    if str(a)=='class':")
print("        print('Username : ',end='')")
print("        q = input()")
print("        if str(q)=='caripeng30':")
print("            print('password : ',end='')")
print("            password4 = input()")
print("            if str(password4)=='Pccaricari':")
print("                #")
print("                print(type('class'))")
print("    if str(a)=='scripts': ")
print("        print('username : ',end='--->>')")
print("        r = input()")
print("        if str(r)=='caripeng30':")
print("            print('Password : ',end=' ')")
print("            password10 = input()")
print("        if str(password10)=='Pccaricari':")
print("            print('''")
print("        import random")
print("import time")
print("from pdb import Restart")
print("for x in range(1000000):")
print("    number = '1234567890'")
print("    s = '1234567890'")
print("    passlen = 9")
print("    x =  ''.join(random.sample(s,passlen ))")
print("    s = '1234567890'")
print("    passlen = 9")
print("    i =  ''.join(random.sample(s,passlen ))")
print("    print('C:/users/Cari Peng/system>',end ='')")
print("    a = input()")
print("    if str(a)=='ls':")
print("        print('2020/6/30 : Cari Birthday')")
print("        print('COVID-19')")
print("        print('Window')")
print("        print('Decoration Script') ")
print("        print('System32')")
print("        print('System64')")
print("        print('2020/6/30 : apps')")
print("    if str(a) == '1':")
print("        print('''+str(a)+'''+'Command Not Found')")
print("    if str(a) == '2':")
print("        print(''' + str(a) + ''' + 'Command Not Found')")
print("    if str(a) == '3':")
print("        print(''' + str(a) + ''' + 'Command Not Found')")
print("    if str(a) == '4':")
print("        print( '''+str(a)+'''+'Command Not Found')")
print("    if str(a) =='5':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='6':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='7':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='8':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='9':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='0':")
print("        print('''+str(a)+'''+'command Not Found')")
print("    if str(a) =='where Cari Birthday':")
print("        print('Cari Birthday : C:/User/2473858/Cari Birthday.txt')")
print("    if str(a) == 'Say Hello':")
print("        print('Hello')")
print("    if str(a) == 'Apk Install Test':")
print("        print('scanning...')")
print("        time.sleep(15)")
print("        print('Scan Finish')")
print("        time.sleep(3)")
print("        print('installing...',end ='')")
print("        print('#',end = '')")
print("        time.sleep(3)")
print("        print('##########',end ='')")
print("        time.sleep(3)")
print("        print('##########',end ='')")
print("        time.sleep(3)")
print("        print('########',end ='')")
print("        time.sleep(3)")
print("        print('Finish')")
print("        ")
print("        ")
print("    if str(a)=='update':")
print("        print('Scanning...')")
print("        time.sleep(15)")
print("        print('Scan Finish')")
print("        time.sleep(0.5)")
print("        print('Updating...',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(3)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='apk install Cari Piano':")
print("        print('Scanning...')")
print("        time.sleep(10)")
print("        print('Scan Finish')")
print("        time.sleep(0.5)")
print("        print('Installing',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(2)  ")
print("    if str(a)=='apk install Python':")
print("        print('Installing Pypi...',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####')")
print("        time.sleep(0.5)")
print("        print('finish installing Pypi')")
print("        time.sleep(0.9)")
print("        print('Installing Python...',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end ='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(2)   ")
print("    if str(a)=='Password':")
print("        print('Enter Password In Input')")
print("    if str(a)=='Pc@cari9809':")
print("        print('KE25A Pc@caricari')   ")
print("    if str(a)=='open.py':")
print("        print('Caculator.py or Multiplications.py')")
print("    if str(a)=='apk install Eclipse IDE':")
print("        print('Scanning')")
print("        time.sleep(5)")
print("        print('download package...')")
print("        time.sleep(3)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('installing...',end ='')")
print("        time.sleep(2)")
print("        print('#####',end ='')")
print("        time.sleep(2)")
print("        print('#####',end ='')")
print("        time.sleep(2)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('scanning Packages...')")
print("        time.sleep(5)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='download Eclipse IDE Packages':")
print("        print('Dowloaidng...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(2)  ")
print("    if str(a)=='window10':")
print("        print('Dowloading System64...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('Downloading Decoration scripts...',end ='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('downloading Apps...',end='')")
print("        time.sleep(0.1)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(5)  ")
print("    if str(a)=='downgrade':")
print("        print('downloading system32...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('Downloading Decoration Scripts...',end='') ")
print("        time.sleep(0.5)    ")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('Downloading apps...',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(3)")
print("        print('##########',end='')")
print("        time.sleep(0.5)")
print("        print('finish')")
print("        time.sleep(0.5)")
print("        print('You Are Window 1.0')")
print("    if str(a)=='android':")
print("        print('Download Android files...')")
print("        time.sleep(5)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('downloading scripts...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('Downloading Apps...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(10)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("    if str(a)=='scan-all':")
print("        print('Scanning...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        print('Scan Result :')")
print("       ")
print("    if str(a)=='update-file':")
print("        print('Checking requirement...')")
print("        time.sleep(0.5)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('updating...',end='')")
print("        time.sleep(0.1)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(0.1)")
print("        print('Scanning...')")
print("        time.sleep(3)")
print("        print('Finish')")
print("        time.sleep(1)")
print("    if str(a)=='apk install Apache_tomcat':")
print("        print('Check requirement...')")
print("        time.sleep(3)")
print("        print('Downloading scripts...')")
print("        time.sleep(3)")
print("        print('Downloading files...')")
print("        time.sleep(0.5)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('installing...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='verifications':")
print("        print('verfications...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('Finish')")
print("        time.sleep(2)")
print("    if str(a)=='del*':")
print("                             ")
print("    if str(a)=='Virus-scan':")
print("        ")
print("        print('scanning...')")
print("        time.sleep(10)")
print("        print('finish')")
print("        time.sleep(0.1)")
print("        print('scan result:')")
print("     ")
print("    if str(a)=='restore':")
print("        print('Restore from recycle bin')")
print("    if str(a)=='startup.sh':")
print("    )")
print("    if str(a)=='imformation-apache-tomcat9.0':")
print(" ")
print("    if str(a)=='commands':")
print("")
print("    if str(a)=='window':")
print("        print('check requirement...')")
print("        time.sleep(3)")
print("        print('Back to window...',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.5)")
print("        print('#####',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(5)")
print("    if str(a)=='quit':")
print("        (0)")
print("    if str(a)=='apk install Java':")
print("        print('downloading files...')     ")
print("        time.sleep(5)")
print("        print('installing...',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(0.5)")
print("        print('##########',end='')")
print("        time.sleep(0.1)")
print("        print('finish')")
print("        time.sleep(2)")
print("    if str(a)=='force-quit':")
print("        (1)  ")
print("    if str(a)=='news':")
print("    if str(a)=='cmd':")
print("        print('version : 1.20.31.0000')")
print("    if str(a)=='title':")
print("        print('Show Title : cmd')")
print("    if str(a)=='rename':")
print("        print('Rename ...:',end=' ')")
print("        i = input()")
print("        print('rename : '+str(i))")
print("    if str(a)=='Batchnew':")
print("        l = input()")
print("        print('Save name : ',end=' ')")
print("        c = input()")
print("        print('Saved : ' + str(c))")
print("    if str(a)=='run batch file':")
print("        if str(l)=='goto crash':")
print("            time.sleep(3)")
print("            print('Your PC has been crashed ')")
print("            print('@#$%^&*())(*&^%$#@!~!@#$%^&*()_)(*&^%$#@')")
print("            time.sleep(5)")
print("            (1)")
print("    if str(a)=='class':")
print("        print('Username : ',end='')")
print("        q = input()")
print("        if str(q)=='publicuser0999847695359':")
print("            print(type)")
print("        else:")
print("            Restart()")
print("    ")
print("        ")
print("       ")
print("    ")
print("                    ")
print("      ")
print("    ")
print("    ")
print("")
print("")
print("")
print("")
print("        ")
print("")
print("   ")
print("    ")
print("            ")
print("                                                                                                                                                                      ''')")
print("    if str(a)=='personnal-imformation':")
print("        print('Username --->>',end =' ')")
print("        pf = input()   ")
print("        if str(pf)=='caripeng30':")
print("            print('Password : ',end =' ')")
print("            password = input()")
print("            if str(password)=='Pccaricari':")
print("                ")
print("                print('Cari's Birthday Is Comming !!!!! 2020 - 06 - 29')")
print("                print('I Like MINECRAFT 2020 - 06 - 29')")
print("                print('Line 830 to edit...')")
print("                print('Chicane 2020 - 06 - 30')")
print("                print('Birthday Cari 2020 - 06 - 30')")
print("                print('Life sucks 2020 - 06 - 30')")
print("            else:")
print("                print('Password incorrect')")
print("        else:")
print("            print('Username incorrect')")
print("    if str(a)=='family':")
print("        print('family code :',end='') ")
print("        codefamily=input() ")
print("        if str(codefamily)=='190882':")
print("            print('User',end='')")
print("            userfamily=input()")
print("            if str(userfamily)==('family190882'):")
print("                print('Door Number',end='')")
print("                passfamily=input()")
print("                if str(passfamily)==('DOOR'):")
print("                    time.sleep(0.5)")
print("                    print('EDIT on line 861')")
print("                    time.sleep(0.5)")
print("                    print('Family Imformation')")
print("                    time.sleep(0.5)")
print("                    print('ACTIVITY : 2020 - 06 - 30 : Cari Birthday - FINISH - ')")
print("                    time.sleep(0.5)")
print("                    print('CALENDAR : 2020 - 07 - 01 : Canada Day -100%-')")
print("                    time.sleep(0.5)")
print("                    print('ACTIVITY : 2020 - 06 - 30 : Cake Cari Birthday - FINISH -')")
print("                    time.sleep(0.5)")
print("                    print('ACTIVITY : 2020 - 06 - 30 : activity Cari Birthday -CENCELED-')")
print("                    time.sleep(0.5)")
print("                    print('CARI : 2020 - 06 - 30 : SPECIAL Minecraft for 2 hours  - FINISHN -')")
print("                    time.sleep(0.5)")
print("                    print('ACTIVITY : 2020 - 06 - 30 PIANO ELECTRIC happy birthday - FINISH -')")
print("                    time.sleep(0.5)")
print("                    print('------------------------------')")
print("                    time.sleep(0.5)")
print("                    print('YING AND DUO DOOR NUMBER CODE : NP80H')")
print("                    time.sleep(0.5)")
print("                    print('CARI NUMBER CODE : KE25A')")
print("                    time.sleep(0.5)")
print("                    print('FAMILY CODE : 190882')")
print("                    time.sleep(0.5)")
print("                    print('-----------------------------')")
print("                    time.sleep(0.5)")
print("                    print('PIANO : very not good 2020 - 06 - 30')")
print("    if str(a)=='new_session':")
print("                print('BROKEN')")
print("                print('Your Name(complete)')")
print("                createusername=input()")
print("                print('Get Code : ')")
print("                s = '123456789012345678901234567890'")
print("                passlen = 30")
print("                passwordgenerator1 =  ''.join(random.sample(s,passlen ))")
print("                createusername2 = '{name:'+str(createusername)+'|code:'+str(passwordgenerator1)+'}'")
print("                print(str(createusername2))")
print("    if str(a)=='login':")
print("        #")
print("                    #")
print("        print('To enter a session, you need to create a session at the command : family-190882')")
print("        print('Login code : ',end='')")
print("        logingetcode=input()")
print("        try:")
print("            if str(logingetcode)==(createusername2):")
print("                #")
print("        #        #")
print("                        #")
print("                    print('Your session '+createusername2+' '+createusername)")
print("                    session=input() ")
print("                    session12=input()")
print("                    session13=input()")
print("                    session14=input()")
print("                    session15=input()")
print("                    session16=input()")
print("            else:")
print("                        #")
print("                print('NO session') ")
print("        except:")
print("            print(' getting info at GET.SYS.INFO.java')")
print("            time.sleep(6)")
print("            for log in range(10000):")
print("                print(str(log)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("                s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("                passlen = 26")
print("                error =  ''.join(random.sample(s,passlen ))")
print("                time.sleep(0.001)")
print("                print (error)       ")
print("            for logc in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.01)")
print("            print('100%')")
print("        #")
print("    if str(a)=='How To Create A New Session':")
print("        print('1.go to family-190882 command')")
print("        print('2. In Your Name (complete) write your name')")
print("        print('3. Get the code and Copy')")
print("        print('4. go to the command login and paste the code')")
print("        print('IF YOU D'ONT PASTE THE CODE, ERROR CRASH')")
print("    if str(a)=='login2':")
print("        print('Login Code : ')")
print("        logincode2=input()")
print("        try:")
print("            if str(logincode2)==(createusername2):")
print("                print(str(session)+''+str(session12)+''+str(session13)+''+str(session14)+''+str(session15)+''+str(session16),end='')")
print("                session2=input()")
print("                session22=input()")
print("                session23=input()")
print("        except:")
print("            print('getting info at : GET.SYS.INFO.JAVA ')")
print("            print(':( Your PC ran into a problem and need to restart :(')")
print("            print('getting info',end='')")
print("            time.sleep(2)")
print("            print('.',end='')")
print("            time.sleep(2)")
print("            print('.',end='')")
print("            time.sleep(2)")
print("            print('.')")
print("            time.sleep(6)")
print("            for login2ccc in range(101):")
print("                print(str(login2ccc)+'%')")
print("                time.sleep(0.1)")
print("        ")
print("    ")
print("            for login2c in range(10000):")
print("                print(str(login2c)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("                s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("                passlen = 26")
print("                error =  ''.join(random.sample(s,passlen ))")
print("                time.sleep(0.001)")
print("                print (error)       ")
print("            for login2cc in range(0,101,1):")
print("                print(str(login2cc)+'%'+'completed')")
print("                time.sleep(0.1)")
print("            time.sleep(6)")
print("    if str(a)=='name':")
print("        for name in range(1):")
print("            #")
print("            s = ('Duo','Cari','Ying')")
print("            passlen = 1")
print("            namegenerator1 =  ''.join(random.sample(s,passlen ))")
print("            print(namegenerator1)  ")
print("    if str(a)=='!@#$%^&*()':")
print("        for i in range(10000):")
print("            print(str(i)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("            passlen = 26")
print("            error =  ''.join(random.sample(s,passlen ))")
print("            time.sleep(0.001)")
print("            print (error)       ")
print("        for v in range(0,101,1):")
print("            print(str(v)+'%'+'completed')")
print("            time.sleep(0.01)")
print("    if str(a)=='SYS.INFO':")
print("        print('system code : ',end='')")
print("        s = '1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'")
print("        passlen = 10")
print("        SYSINFO =  ''.join(random.sample(s,passlen ))")
print("        print(SYSINFO) ")
print("    if str(a)=='exit(0)':")
print("        print('do you want to exit? port 0(y/n)',end='')")
print("        exit0=input()")
print("        if str(exit0)=='y':")
print("            exit(0)        ")
print("        else:")
print("            print('')")
print("    if str(a)=='exit(1)':")
print("        print('exit on port 1')")
print("        exit(1)")
print("    if str(a)=='internet':")
print("        print('URL--->>',end=' ')")
print("        url=input()")
print("    try:")
print("        if str(url)=='caripiano.music.blog':")
print("            print('exist')")
print("        elif str(url)=='caripeng.car.blog':")
print("            print('exist')")
print("        elif str(url)=='canada.ca':")
print("            print('exist')")
print("        else:")
print("            print('')")
print("    except:")
print("        point+=0.001")
print("    if str(a)=='find .':")
print("        print('find system')")
print("        time.sleep(0.1)")
print("        print('decoration')")
print("        time.sleep(0.1)")
print("        print('personnal')")
print("        time.sleep(0.1)")
print("        print('other')")
print("    if str(a)=='not_responding':")
print("        print('try to click the X (the turtle program)')")
print("        myTurtle = turtle.Turtle(shape='arrow')")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-10, 10)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-20,20)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-30, 30)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-40, 40)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-50, 50)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(10,-10)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(20, -20)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(30, -30)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(40, -40)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(50, -50)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(-50,-50)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-40, -40)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(-30, -30)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(-20, -20)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(-10, -10)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(50,50)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(40, 40)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.penup()")
print("        myTurtle.setposition(30, 30)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(20, 20)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        myTurtle.setposition(10, 10)")
print("        myTurtle.pendown()")
print("        myTurtle.circle(1)")
print("        turtle.done()")
print("        time.sleep(3)")
print("        print('script need to terminate')")
print("        for n in range(10000):")
print("            print(str(n)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("            passlen = 26")
print("            error =  ''.join(random.sample(s,passlen ))")
print("            time.sleep(0.001)")
print("            print (error)       ")
print("        for w in range(0,101,1):")
print("            print(str(w)+'%'+'completed')")
print("            time.sleep(0.01)")
print("        time.sleep(6)")
print("        exit()")
print("    if str(a)=='kill sys.sys':")
print("        print('getting info at : GET.SYS.INFO.java')")
print("        time.sleep(6)")
print("        for b in range(10000):")
print("            print(str(b)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("            passlen = 26")
print("            error =  ''.join(random.sample(s,passlen ))")
print("            time.sleep(0.001)")
print("            print (error)       ")
print("        for z in range(0,101,1):")
print("            print(str(z)+'%'+'completed')")
print("            time.sleep(0.01)")
print("        time.sleep(6)")
print("    if str(a)=='open.all':")
print("        class CustomError(Exception):")
print("            pass")
print("        raise SystemError('To Many App Open crash32')")
print("    if str(a)=='kill service.localhost':")
print("        print('getting info at : GET.SYS.INFO.java')")
print("        time.sleep(6)")
print("        for kill in range(10000):")
print("            print(str(kill)+'ERROR:'+'file:'+'190882/family/system/code:',end='')")
print("                #")
print("            s = 'abcdefgh8jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123457890'")
print("            passlen = 26")
print("            error =  ''.join(random.sample(s,passlen ))")
print("            time.sleep(0.001)")
print("            print (error)       ")
print("        for crashkill in range(0,101,1):")
print("            print(str(crashkill)+'%'+'completed')")
print("            time.sleep(0.01)")
print("        time.sleep(6)")
print("    if str(a)=='del* sys.sys.all':")
print("        print('do you want to delete 9000 file (y/n)',end='')")
print("        delete = True")
print("        comfirmdel1=input()")
print("        if str(comfirmdel1)=='y':")
print("            for x in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.5)")
print("            print('100%')")
print("    if str(a)=='apk change sys.sys.update.upgrade.win10.all.*.fast.100':")
print("        print('comfirm (y/n)')")
print("        comfirmupgadewin101=input()")
print("        if str(comfirmupgadewin101)=='y':")
print("            for x in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.1)")
print("            print('100%')")
print("    if str(a)=='windows7.windows10.*':")
print("        print('comfirm (y/n)')")
print("        comfirmsystem7system10=input()")
print("        if str(comfirmsystem7system10)=='y':")
print("            for x in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.5)")
print("            print('100%')")
print("    if str(a)=='exe install Minecraft JE':")
print("        print('comfirm (y/n)')")
print("        comfirmminecraftexeinstallje=input()")
print("        if str(comfirmminecraftexeinstallje)=='y':")
print("            print('file...')")
print("            for x in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.1)")
print("            print('100%')")
print("            print('download...')")
print("            for x in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.5)")
print("            print('100%')")
print("    if str(a)=='run.eclipseIDE':")
print("        print('starting eclipse IDE...')")
print("        for runeclipseide in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        inputeclipseide=input()")
print("        if str(inputeclipseide)=='':")
print("            print('this is a test')")
print("    if str(a)=='vmware':")
print("        print('starting up...')")
print("        for vmware in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        print('command line can not startup in vmware. PLease start the command line on a real PC :(')")
print("        ")
print("    if str(a)=='virtual.machine':")
print("        print('Please wait...')")
print("        for vm in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.3)")
print("        print('100%')")
print("        print('can not use virtual machine')")
print("    if str(a)=='pay':")
print("        print('___$')")
print("        pay=input()")
print("        print('To __')")
print("        payto=input()")
print("        print('****')")
print("        passpay=input()")
print("        if str(pay)=='':")
print("            print('please retry')")
print("        else:")
print("            #")
print("            print('pay'+':'+str(pay)+'$ '+ ' to '+str(payto))")
print("            for x in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.1)")
print("            print('100%')")
print("        if str(passpay)=='passpay':")
print("            print('approved')")
print("        else:")
print("            print('result :',end=' ')")
print("            print('CENCELED')")
print("    if str(a)=='shutdown.sys':")
print("        print('...')")
print("        for shutsys in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        time.sleep(3)")
print("        exit(0)")
print("    if str(a)=='apk install Cari Piano2':")
print("        print('installing 999.9999999.MO')")
print("        for x in range(100):")
print("            print('#',end='')")
print("            time.sleep(1)")
print("        print('100%')")
print("    if str(a)=='disconnect.net':")
print("        print('disconnected')")
print("    if str(a)=='connect.net':")
print("        print('connecting...')")
print("        for netconnect in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.01)")
print("        print('finish')")
print("    if str(a)=='restart':")
print("        print('restarting...')")
print("        for restartsys1 in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('...')")
print("        time.sleep(10)")
print("        print('starting up...')")
print("        os.startfile('C:/Users/2473858/Desktop/1.mp3')")
print("        for x in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        print('connect to internet (net)')")
print("        for connectrestartsys1 in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.01)")
print("        print('finish')")
print("        print('...')")
print("        time.sleep(3)        ")
print("    if str(a)=='sleep':")
print("        print('...')")
print("        for sleepsys1 in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.01)")
print("        print('100%')")
print("        exit()")
print("    if str(a)=='cd perssonnal/CARI PENG':")
print("        print('/perssonnal/CARI PENG',end='')")
print("        cdperssonnalCARIPENG=input()")
print("        if str(cdperssonnalCARIPENG)=='del':")
print("            print('comfirm (y/n)')")
print("            comfirmdelcdperssonnalCARIPENG=input()")
print("            if str(comfirmdelcdperssonnalCARIPENG)=='y':")
print("                delete = True")
print("                print('deleting...')")
print("                for x in range(100):")
print("                    print('#',end='')")
print("                    time.sleep(0.1)")
print("                print('100%')")
print("        if str(cdperssonnalCARIPENG)=='dir':")
print("            print('HTML')")
print("            print('PYTHON')")
print("            print('CSS')")
print("            print('PHP')")
print("            print('??? 2020 -06')")
print("            print('COMPRESSED 2020 -06')")
print("            print('OTHER 2020 - 06')")
print("    if str(a)=='cd perssonnal/CARI PENG/HTML':")
print("        print('perssonnal/CARI PENG/HTML')")
print("        inputperssonnalCARIPENGhtml=input()")
print("        if str(inputperssonnalCARIPENGhtml)=='del':")
print("            print('comfirm (y/n)')")
print("            comfirmdelcdperssonnalCARIPENGHTML=input()")
print("            if str(comfirmdelcdperssonnalCARIPENGHTML)=='y':")
print("                delete = True")
print("                print('deleting...')")
print("                for comfirmdelcdperssonnalCARIPENGHTML2 in range(100):")
print("                    print('#',end='')")
print("                    time.sleep(0.1)")
print("                print('100%')")
print("        if str(inputperssonnalCARIPENGhtml)=='dir':")
print("            print('my_table.html')")
print("            print('progress.html')")
print("            print('multiplications.html')")
print("            print('index.html')")
print("            print('index.html')")
print("            print('script.html')")
print("            print('...')")
print("    if str(a)=='note-script':")
print("        print('username:')")
print("        usernamenotescript=input()")
print("        if str(usernamenotescript)=='caripeng30':")
print("            print('password:')")
print("            passwordnotescript=input()")
print("            if str(passwordnotescript)=='pass.scr.note':")
print("                print('edit on line 1406')")
print("                print('finish CD explorer')")
print("                print('make for - in range progress')")
print("    if str(a)=='bug':")
print("        print('1 bug')")
print("                   ")
print("    if str(a)=='copy.sys.sys.exe':")
print("        print('Finish')")
print("    if str(a)=='run copy.sys.sys.exe':")
print("        class CustomException(Exception):")
print("            pass")
print("        raise CustomException('can not run system')")
print("    if str(a)=='r.pi':")
print("        class CustomException(Exception):")
print("            pass")
print("        raise SystemError(' I D'ont Like Piano')")
print("    if str(a)=='reset.pc':")
print("        print('comfirm (y/n)')")
print("        comfirmresetpc1=input()")
print("        if str(comfirmresetpc1)=='y':")
print("            print('deleting file...')")
print("            for deletefilerestepc in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.5)")
print("            print('100%')")
print("            print('reinstalling System...')")
print("            for reinstallingwindowsresetpc1 in range(100):")
print("                print('#',end='')")
print("                time.sleep(1)")
print("            print('100%')")
print("            print('setup is checking your computer',end='')")
print("            time.sleep(3)")
print("            print('.',end='')")
print("            time.sleep(3)")
print("            print('.',end='')")
print("            time.sleep(3)")
print("            print('.')")
print("            for setupcheckingpc in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.5)")
print("            print('100%')")
print("            print('Please Wait...')")
print("            for pleasewait in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.3)")
print("            print('FINISH')")
print("            time.sleep(3)")
print("            print('loading',end='')")
print("            time.sleep(3)")
print("            print('.',end='')")
print("            time.sleep(3)")
print("            print('.',end='')")
print("            time.sleep(3)")
print("            print('.')")
print("            time.sleep(10)")
print("    if str(a)=='ERRORexceptionPID19283345':")
print("        class CustomException(Exception):")
print("            pass")
print("        raise SystemError('SUCCESS:ERRORexceptionPID19283345')")
print("    if str(a)=='__END__':")
print("        print('Terminate Computer')")
print("        class CustomException(Exception):")
print("            pass")
print("        raise SystemError('Computer BROKEN Please buy a new computer')")
print("    if str(a)=='add.doc':")
print("        os.startfile('C:/Users/2473858/Desktop//APPLICATION ERROR.exe')")
print("        time.sleep(5)")
print("    if str(a)=='start':")
print("        os.startfile('C:/Users/2473858/Documents/Python//cmd.py')")
print("    if str(a)=='Chrome':")
print("        os.startfile('C:/Program Files (x86)/Google/Chrome/Application//chrome.exe')")
print("    if str(a)=='explorer':")
print("        os.startfile('C:/Users/2473858')")
print("    if str(a)=='errorx10':")
print("        for errorxdix in range(10):")
print("            os.startfile('C:/Users/2473858/Desktop/APPLICATION ERROR.exe')")
print("    if str(a)=='file':")
print("        print('file')")
print("        fileinput=input()")
print("        try:")
print("            os.startfile(fileinput)")
print("        except:")
print("            print('can not find the file')   ")
print("    if str(a)=='web':")
print("        print('https://',end='')")
print("        web=input()")
print("        os.startfile('https://'+(web))")
print("    if str(a)=='word':")
print("            #")
print("        os.startfile('C:/windows/write')")
print("    if str(a)=='microsoft.VSTUDIO':")
print("        print('downloading packages...')")
print("        for downpack_mirosoft in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        print('installing packages...')")
print("        print('microsoft.debugger.VSTUDIO')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.policy...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.editor...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack1...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack80...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack100...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.runpack0...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.debugger_pack90...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.editor_pack800...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.script.pack60...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSSTUDIO.copy_paste_pack90...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack19')")
print("        for microsoft_VSTUDIO_pack in range(262):")
print("            print('microsoft.VSTUDIO.pack'+str(microsoft_VSTUDIO_pack)+'...')")
print("            time.sleep(0.1)")
print("        print('finish')")
print("        for end_PROGRESS_microsoft_VSTUDIO in range(100):")
print("            print('=',end='')")
print("            time.sleep(0.1)")
print("        print('FINISH')")
print("        time.sleep(3)")
print("    if str(a)=='install.UNITY3D.exe':")
print("        for prepa_unity_3d_install in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('installing...')")
print("        print('downloading packages...')")
print("        for downpack_mirosoft in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        print('installing packages...')")
print("        print('microsoft.debugger.VSTUDIO')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.policy...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.editor...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack1...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack80...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack100...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.runpack0...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.debugger_pack90...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.editor_pack800...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.script.pack60...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSSTUDIO.copy_paste_pack90...')")
print("        time.sleep(0.5)")
print("        print('microsoft.VSTUDIO.pack19')")
print("        for microsoft_VSTUDIO_pack in range(262):")
print("            print('microsoft.VSTUDIO.pack'+str(microsoft_VSTUDIO_pack)+'...')")
print("            time.sleep(0.1)")
print("        print('finish')")
print("        for end_PROGRESS_microsoft_VSTUDIO in range(100):")
print("            print('=',end='')")
print("            time.sleep(0.1)")
print("        print('FINISH')")
print("        time.sleep(3)")
print("    if str(a)=='systeminfo':")
print("        print('loading...')")
print("        time.sleep(0.1)")
print("        print('loading system info...')")
print("        for loading_pack_systeminfo in range(263):")
print("            ")
print("            print('loading pack'+str(loading_pack_systeminfo)+'...')")
print("            time.sleep(0.1)")
print("            print('''")
print("            Host Name:                 CARI-PC")
print("OS Name:                   system 10 Family")
print("OS Version:                10.0.18363 N/A Build 18363")
print("OS Manufacturer:           Cari Peng ")
print("OS Configuration:          Standalone Workstation")
print("OS Build Type:             Multiprocessor Free")
print("Registered Owner:          Cari Peng")
print("Registered Organization:")
print("Product ID:                098-776-55443")
print("Original Install Date:     4/1/2020, 12:03:24 AM")
print("System Boot Time:          7/9/2020, 12:03:31 PM")
print("System Manufacturer:       190882_FAMILY")
print("System Model:              190882KE25ANP80H")
print("System Type:               x86-based PC")
print("Processor(s):              10 Processor(s) Installed.")
print("                           [01]: SYSTEM64 Family 18 Model 1 Stepping 0 AuthenticAMD ~1500 Mhz")
print("BIOS Version:              SYSTEM 1.12")
print("perssonal Directory:       190882/family/perssonal")
print("System Directory:          190882/family/system")
print("Boot Device:               \Device\HarddiskVolume2")
print("System Locale:             en-ca;English (Canada)")
print("Input Locale:              en-us;English (United States)")
print("Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)")
print("Total Physical Memory:     5,611 MB")
print("Available Physical Memory: 2,756 MB")
print("Virtual Memory: Max Size:  11,243 MB")
print("Virtual Memory: Available: 8,222 MB")
print("Virtual Memory: In Use:    3,021 MB")
print("Domain:                    190882_FAMILY_SYSTEM")
print("Logon Server:              \\CARI-PC")
print("Hotfix(s):                 12 Hotfix(s) Installed.")
print("                           [01]: KB4552931")
print("                           [02]: KB4513661")
print("                           [03]: KB4516115")
print("                           [04]: KB4517245")
print("                           [05]: KB4528759")
print("                           [06]: KB4537759")
print("                           [07]: KB4541338")
print("                           [08]: KB4552152")
print("                           [09]: KB4559309")
print("                           [10]: KB4560959")
print("                           [11]: KB4561600")
print("                           [12]: KB4560960")
print("Network Card(s):           2 NIC(s) Installed.")
print("                           [01]: Qualcomm Atheros AR5B97 Wireless Network Adapter")
print("                                 Connection Name: Wi-Fi")
print("                                 DHCP Enabled:    Yes")
print("                                 DHCP Server:     192.168.3.1")
print("                                 IP address(es)")
print("                                 [01]: 192.168.3.129")
print("                           [02]: Broadcom NetLink (TM) Gigabit Ethernet")
print("                                 Connection Name: Local Area Connection")
print("                                 Status:          Hardware not present")
print("Hyper-V Requirements:      VM Monitor Mode Extensions: Yes")
print("                           Virtualization Enabled In Firmware: Yes")
print("                           Second Level Address Translation: Yes")
print("                           Data Execution Prevention Available: Yes")
print("                                                                                           ''')")
print("            print('can not print all')")
print("    if str(a)=='download Minecraft':")
print("        print('downloading...')")
print("        for down_file_java_file in range(1001):")
print("            print('packages.mojang.MCJE_'+str(down_file_java_file) + '.java '+str(down_file_java_file)+' of 1000')")
print("            time.sleep(0.01)")
print("        for mojang_installing_MC in range(100):")
print("            s = 'abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'")
print("            passlen = 100")
print("            mojang_install_MC2 =  ''.join(random.sample(s,passlen ))")
print("            print ('downloading : '+str(mojang_install_MC2)+' type : folder'+' Publisher : Mojang ')")
print("            time.sleep(0.1)")
print("        print('Download MCpack.MCPE...')")
print("        time.sleep(0.7)")
print("        print('download Run.MCPE.INst.setup')")
print("        time.sleep(0.1)")
print("        print('Completing Downloads... Please wait...')")
print("        time.sleep(6)")
print("        print('FINISH')")
print("        time.sleep(0.2)")
print("        print('Preparing to running script...')")
print("        time.sleep(3)")
print("        for downinst_MCJE_FOR_IN_RANGE in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.3)")
print("        print('FINISH')")
print("        time.sleep(3)")
print("        print('Please Wait...')")
print("    if str(a)=='VIRUS.SCAN_SYS':")
print("        comfirm_scan_virus_key=input('Press ENTER to continue... Else use quit to quit')")
print("        if comfirm_scan_virus_key=='':")
print("            print('scanning...')")
print("            for scan_virus_sys in range(100):")
print("                print('#',end='')")
print("                time.sleep(0.1)")
print("            print('100%')")
print("            print('NO VIRUS FOOUND!')")
print("            ")
print("        ")
print("        time.sleep(3)")
print("        print('FINISH')")
print("    if str(a)=='Cari':")
print("        print('H',end='')")
print("        time.sleep(0.2)")
print("        print('e',end='')")
print("        time.sleep(0.2)")
print("        print('l',end='')")
print("        time.sleep(0.2)")
print("        print('l',end='')")
print("        time.sleep(0.2)")
print("        print('o',end='')")
print("        time.sleep(0.2)")
print("        print(',',end='')")
print("        print(' ',end='')")
print("        time.sleep(0.2)")
print("        print('m',end='')")
print("        time.sleep(0.2)")
print("        print('y',end='')")
print("        time.sleep(0.2)")
print("        print(' ',end='')")
print("        time.sleep(0.2)")
print("        print('n',end='')")
print("        time.sleep(0.2)")
print("        print('a',end='')")
print("        time.sleep(0.2)")
print("        print('m',end='')")
print("        time.sleep(0.2)")
print("        print('e')")
print("        time.sleep(0.2)")
print("        print('is Cari.')")
print("        time.sleep(0.2)")
print("        print('')")
print("        time.sleep(0.2)")
print("        for mynameno in range(200):")
print("            print('-',end='')")
print("            time.sleep(0.01)")
print("        print('-')")
print("    if str(a)=='Install Virus':")
print("        trueflase = False")
print("        for progvirusinst in range(100):")
print("            print('#',end='')")
print("            time.sleep(0.1)")
print("        print('100%')")
print("        print('Finish')")
print("    if str(a)=='CHEAT:_update_truefalse:True':")
print("        trueflase = True")
print("    if str(a)=='CHEAT:_update_truefalse:False':")
print("        trueflase = False")
print("    if str(a)=='True False':")
print("        if trueflase == True:")
print("            print('No Virus True')")
print("        else:")
print("            print('VIRUS False')")
print("    if str(a)=='CPL':")
print("        print('Point + 1')")
print("        point+=1")
print("    if str(a)=='CPP':")
print("        print('point:'+str(point))")
print("    if str(a)=='CPPclear':")
print("        print('Clearing ALL')")
print("        point=0.000000000000000000000000001")
print("    if str(a)=='time':")
print("        for time1 in range(1):")
print("            #")
print("            now = datetime.now()")
print("            current_time = now.strftime('%D %H:%M:%S')")
print("            print(current_time)")
print("            time.sleep(1)")
print("    if str(a)=='Save.note':")
print("        print('Save')")
print("        save_note=input()")
print("        save_note1=save_note")
print("    if str(a)=='open save.note':")
print("        try:")
print("            print(save_note1)")
print("        except:")
print("            print('Save.note do not exist')")
print("    if str(a)=='CHEAT:_get.permCP19:True':")
print("        permCP19=True")
print("        print('Updated')")
print("    if str(a)=='abcp19':")
print("        try:")
print("            if permCP19 == True:")
print("                print('Nothing Test')")
print("            else:")
print("                print('please get permCP19')")
print("        except:")
print("            print('Please Get permCP19')")
print("    if str(a)=='CHEAT:_del.permCP19:False':")
print("        print('Updated')")
print("    if str(a)=='Restart.sys':")
print("        print('restarting...')")
print("        os.startfile('C:/Users/2473858/Documents/Python//cmd.py')")
print("        time.sleep(0.1)")
print("        exit(0)")
print("        permCP19=False")
print("    def CAPSLOCK_STATE():")
print("        hllDll = ctypes.WinDLL ('User32.dll')")
print("        VK_CAPITAL = 0x14")
print("        return hllDll.GetKeyState(VK_CAPITAL)")
print("")
print("    CAPSLOCK = CAPSLOCK_STATE()")
print("    if ((CAPSLOCK) & 0xffff) != 0:")
print("        print('\n CAPS LOCK IS ON\n')")
print("    import json")
print("    if str(a)=='saving json file':")
print("        nameJson1 = input('Username')")
print("        passwordJson1 = input('Password')")
print("        letters = (str(nameJson1)+str(passwordJson1))")
print("")
print("        numbers = []")
print("        for letter in letters:")
print("            for JsonTestP in  range(1):")
print("                #")
print("                number = ord(letter) - 96")
print("                numbers.append(number)")
print("")
print("        print(numbers)")
print("        jsonfile1 = {")
print("        'info':(numbers)")
print("        }")
print("")
print("        with open('INFO'+(nameJson1), 'w') as json_file:")
print("            json.dump(jsonfile1, json_file)")
print("    if str(a)=='un-install sys':")
print("           ")
print("        ")
print("        ")
print("        try:")
print("            os.remove('C:/Users/2473858/Desktop//INFO')")
print("            os.remove('C:/Users/2473858/Desktop//INFO2system')")
print("        except:")
print("            print('ERROR')")
print("    if str(a)=='version':")
print("        version = 19")
print("        versionb = 15.19")
print("        print(version//versionb//1915.1915++version//versionb)")
print("    if str(a)=='main.sh':")
print("        print('starting main.sh...')")
print("        main = input('wating for fuel...')")
print("        if str(main)=='st':")
print("            if fuelrobot==0:")
print("                print('no perm to start')")
print("            else:")
print("                fuelrobot-=1")
print("                print('starting up...')")
print("                for main0 in range(10):")
print("                    for main1 in range(1, 50):")
print("                        for main2 in range(1, main1):")
print("                            print('#',end='')")
print("                            time.sleep(0.001)")
print("                        print(' ')")
print("            print('FINISH')")
print("    if str(a)=='perm+':")
print("        print('checking...')")
print("        if coin==0:")
print("            print('no coin')")
print("        else:")
print("            print('add perm !')")
print("            fuelrobot+=2")
print("            coin-=2")
print("    if str(a)=='coin':")
print("        print(coin)")
print("    if str(a)=='perm':")
print("        print(fuelrobot)")
print("    if str(a)=='coin+f':")
print("        print('Cheacking...')")
print("        if fuelrobot==0:")
print("            print('No perm to add.')")
print("        else:")
print("            coin+=1")
print("    if str(a)=='coin+self':")
print("        print('Checking...')")
print("        if reself==0:")
print("            print('Bad Chance :(')")
print("        else:")
print("            coin+=10")
print("            reself-=1")
print("    if str(a)=='self':")
print("        print(reself)")
print("    if str(a)=='trianglesPYex':")
print("        print('Checking...')")
print("        if fuelrobot==0:")
print("            print('No Perm')")
print("        else:")
print("            fuelrobot-=1")
print("            print('''")
print("        for i in range(1, 10):")
print("            for j in range(1, i):")
print("                print('*')")
print("            print(' ')")
print("    result :")
print("    ")
print("    *")
print("    **")
print("    ***")
print("    ****")
print("    *****")
print("    ******")
print("    *******")
print("    ********")
print("    *********")
print("    **********")
print("                                                        ''')")
print("    if str(a)=='vim system/info/boot.txt':")
print("        print('Boot imformation : Boot from Hard Drive')")
print("    if str(a)=='vim var/vrash/bootc.dll':")
print("        print('acess denied')")
print("    if str(a)=='cd system/sysWOW64':")
print("        print('acess denied')")
print("    if str(a)=='vim system/boot/bootsys.dll':")
print("        print('Acess denied')")
print("    if str(a)=='vim lin/start/boot.dll':")
print("        print('acess denied')")
print("    if str(a)=='exit':")
print("        exit(0)")
print("    if str(a)=='re':")
print("        os.startfile('C:/Users/2473858/Documents/Python/cmd.py')")
print("        exit(0)")
print("    if str(a)=='coin.':")
print("        coina=input()")
print("        if str(coina)=='transform-perm+':")
print("            print('Verifing...')")
print("            if coin==0:")
print("                print('No coin')")
print("                coin+=1")
print("                time.sleep(0.5)")
print("                reself-=1")
print("                time.sleep(0.5)")
print("                fuelrobot+=1")
print("                coin-=1")
print("                print('Finish')")
print("            else:")
print("                fuelrobot+=1")
print("                coin-=1")
print("                print('Finish')")
print("        if str(coina)=='coin-self+':")
print("            print('...')")
print("            if coin==0:")
print("                print('No action needed')")
print("            else:")
print("                coin-=1")
print("                reself+=1")
print("                print('Finish')")
print("        if str(coina)=='transform-coin+':")
print("            if reself==0:")
print("                print('No Self')")
print("            else:")
print("                reself-=5")
print("                coin+=50")
print("                ")
print("                                                  ")
print("    ")
print("")
print("</textarea>")
print("</body>")
print("</html>")

