#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Accept Cookies Policy</title>")
print("<style>")
print("body {")
print("background-color: #0088cc;")
print("}")
print("input {")
print("background-color: #006699;")
print("color: White;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<hr></hr>")
print("<h1><center>Accept Cookie Policy</center></h1>")
print("<hr></hr>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<p><center>Please accept cookie Policy To Continue</center></p>")
print("<form method='POST' action='0999847695359.py'.py>")
print("<center><input type='checkbox' name='cookiesPolicy' required></center>")
print("<center><input type='submit' value='continue'>")
print("</form>")
print("</body>")
print("</html>")

