#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Page Title</title>")
print("<style>")
print("textarea {")
print("background-color: black;")
print("font-family: courier;")
print("color: white;")
print("font-size:13px;")
print("width: 1355px;")
print("height: 600px;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<div>")
print("<form>")
print("<textarea  name='404notfoundtomcat9ubuntupenggroup' cols=1 rows=1 placeholder = 'Enter your code'>")
print("<!doctype HTML>")
print("<html>")
print("<head>")
print("<title>Page Title</title>")
print("<!Style goes here !>")
print("</head>")
print("<body>")
print("<h1>This is a heading</h1>")
print("<p>This is a paragraph</p>")
print("</body>")
print("</html>")
print("</textarea>")
print("</body>")
print("</html>")

