#!/usr/bin/python3

#`print("<!--Rename as _img_src_PLS_login-->")
print ("Content-type:text/html\n\n") 
print("<html>")
print("<head>")
print("<meta name='viewport' content='width=device-width, initial-scale=1'>")
print("<link rel='stylesheet' href='../../css/ecurtains.css'>\n")
print("<style>")
print("</style>")
print("</head>")
print("<body>")
print("")
print("")
print("<div class='header' id='myHeader'>")
print("  <h2><a href='home'> Home </a><a href='product'> Products </a> <img src='_img_src_pls' alt='_img_src_PLS_login'></h2>")
print("</div>")
print("<!--Please keep this script here dont move again-->")
print("<script>")
print("window.onscroll = function() {myFunction()};")
print("")
print("var header = document.getElementById('myHeader');")
print("var sticky = header.offsetTop;")
print("")
print("function myFunction() {")
print("  if (window.pageYOffset > sticky) {")
print("    header.classList.add('sticky');")
print("  } else {")
print("    header.classList.remove('sticky');")
print("  }")
print("}")
print("</script>")
print("<!--Please dont move this script again-->")
print("<div class='content'>")
print("  <!--some texte here-->")
print("  <h2>Normal curtain...</h2>")
print("  <table>")
print("      <td>")
print("        <tr>  EMPTY</tr>")
print("        <tr>  EMPTY</tr>")
print("        <tr>  EMPTY</tr>")
print("        <tr>  EMPTY</tr>")
print("        <tr>  EMPTY</tr>")
print("        <tr>  EMPTY</tr>")
print("        <tr>  EMPTY</tr>")
print("        ")
print("      </td>")
print("  </table>")
print("  <hr>")
print("  <h2> Other type of curtain.. </h2>")
print("  <table>")
print("    <td>")
print("      <tr>EMPTY</tr>")
print("    </td>")
print("  </table>")
print("  <hr>")
print("</div>")
print("")
print("")
print("")
print("</body>")
print("</html>")
print("<!--eCurtain copyright liences-->")
