#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<title>Page Title</title>")
print("<style>")
print("button {")
print("width: 500px;")
print("height: 12px;")
print("position: -webkit-sticky;")
print("position: sticky;")
print("top: 0;")
print("}")
print(".HeaderIMGContainer {")
print("position: absolute;")
print("top: 50%;")
print("left: 50%;")
print("transform: translate(-50%, -50%);")
print("}")
print(".container {")
print("  position: relative;")
print("  text-align: center;")
print("  color: white;")
print("}")
print(".dropdown {")
print("  position: relative;")
print("  display: inline-block;")
print("  width: 500px;")
print("}")
print(".dropbtn {")
print("  background-color: #4CAF50;")
print("  color: white;")
print("  padding: 16px;")
print("  font-size: 16px;")
print("  border: none;")
print("}")
print("")
print(".dropdown {")
print("  position: relative;")
print("  display: inline-block;")
print("}")
print("")
print(".dropdown-content {")
print("  display: none;")
print("  position: absolute;")
print("  background-color: #f1f1f1;")
print("  min-width: 500px;")
print("  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);")
print("  z-index: 1;")
print("}")
print("")
print(".dropdown-content a {")
print("  color: black;")
print("  padding: 12px 16px;")
print("  text-decoration: none;")
print("  display: block;")
print("}")
print(".dropdown-content a:hover {background-color: #ddd;}")
print("")
print(".dropdown:hover .dropdown-content {display: block;}")
print("")
print(".dropdown:hover .dropbtn {background-color: #3e8e41;}")
print("")
print("</style>")
print("</head>")
print("<body>")
print("")
print("<div class='HeaderIMGContainer'>")
print("  <img src='notDefined' alt='Not Defined' title='Line *' style='width:100%'>")
print("  <div class='HeaderIMGContainer'><h1>Welcome to ECurtain</h1></div>")
print("</div>")
print("<div class='dropdown'>")
print("  <button class='dropbtn'>Menu</button>")
print("  <div class='dropdown-content'>")
print("  <center>")
print("    <a href='#'>Link 1</a>")
print("    <a href='#'>Link 2</a>")
print("    <a href='#'>Link 3</a>")
print("    </center>")
print("  </div>")
print("</div>")
print("</body>")
print("</html>")

