#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<HTML>")
print("<HEAD><TITLE>Login Page</TITLE><HEAD>")
print("<style>")
print("body {")
print("background-color: #0088cc;")
print("}")
print("p {")
print("color: white;") 
print("}")
print("input {")
print("color: white;")
print("background-color: #006699;")
print("}")
print(".line {")
print("background-color: #ffffff;")
print("height: 1px;")
print("}")
print("h6  {")
print("font-family: sans-serif;")
print("color: White;")
print("}")
print("h1 {")
print("color: White;")
print("font-family: tohama, arial, sans-serif;")
print("}")
print("</style>")
print("<CENTER>")
print("<hr class='line'/>")
print("<h1>Login Page</h1>")
print("<hr class='line'/>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("<div id=google_translate_element></div>")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<FORM method='POST' action='start.py'>")

print("<p><center> Enter your login name: <input type='text' name='login' value='Username' required></center></p>")

print("<p><center> Enter your password: <input type=password name='password' value='python' required><center></p>")

print("<p> <input type='submit' value='Login'></p>")
print("</FORM>")
print("<h4><center>Click <a href='signup.py'>here</a> to Sign up</center></h4>")
print("<hr class='line'/>")
print("<h6>(c) website </hr></h6>")
print("<hr class='line'/>")
print("</CENTER>")
print("</body>")
print("</HTML>")
