#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Minecraft</title>")
print("<style>")
print("body {")
print("background-color: green;")
print("font-family: tahoma;")
print("}")
print("question {")
print("color: yellow;")
print("background-color: black;")
print("}")
print("a:link {")
print("color: Red;")
print("background-color: transparent;")
print("text-decoration: none;")
print("}")
print("font {")
print("font-family: courier;")
print("cont-size: 12px;")
print("}")
print("</style>")
print("</head>")
print("<center>")
print("<body>")
print("<h1>Minecraft</h1>")
print("<div id='google_translate_element'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<p> Minecraft is a Game.</p>")
print("<h4>Fishing in Lava</h4>")
print("<p>Have you tried fishing in lava? <a href='mailto:caripeng30@gmail.com'>Say...</a></p>")
print("<h4>Best way to mine Diamonds</h4>")
print("<p>Wath is your best way to mine diamonds ? How many diamonds you have ?")
print("64, 32, 18, 7, ...<a href='mailto:caripeng30@gmail.com'>Say...</a></p>")
print("<h4>Secrets Block</h4>")
print("<p>Minecraft have secret block : Commands Block, structure block. You can not use these block in survival and adventure. Blocks : Commands_block , Structure_block. <a href='mailto:caripeng30@gmail.com'>I Know !</a></p>")
print("<h4><question>Question</question></h4>")
print("<p>Do you like Minecraft ? <a href='mailto:caripeng30@gmail.com'>Answer</a></p>")
print("<h4><question>Question</question></h4>")
print("<p>Do you like fishing ? <a href='mailto:caripeng30@gmail.com'>Answer</a></p>")
print("<p><font>By Cari Peng | You can download minecraft | <a href='https://minecraft.net'>Go to minecraft.net</a></font></p>")
print("</body>")
print("</center>")
print("</html>")

