#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>HTTP status 000 - Not Available</title>")
print("<style type='text/css'>")
print("h1, h2, h3 b {")
print("color: white;")
print("background-color: #525D76;")
print("}")
print("body {")
print("font-family: Tahoma, Arial, Sans-serif;")
print("}")
print("h1 {")
print("font-size: 22px;")
print("}")
print("h2 {")
print("font-size: 16px;")
print("}")
print("h3 {")
print("font-size: 14;")
print("}")
print("p {")
print("font-size: 12px;")
print("}")
print("a {")
print("color: black;")
print("}")
print(".line {")
print("height: 1px;")
print("background-color: #525D76;")
print("border: none;")
print("}")
print("b {")
print("color: white;")
print("background-color: #525D76;")
print("}")
print("h4 {")
print("color: white;")
print("background-color: #525D76;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("")
print("<h1>HTTP status 000 - Not Available</h1>")
print("<hr class='line'/>")
print("<p><b>Type</b> Not available Page</p>")
print("<p><b>Description</b> This Page is not available in this Site</p>")
print("<hr class='line'/>")
print("<h4>Apache Tomcat/9.0.31(Ubuntu)</h4>")
print("</body>")
print("</html>")
