#!/usr/bin/python3
print("Content-type: text/html\n\n");
print("<html>")
print("<head>")
print("<title>Link</title>")
print("<style>")
print("table, th, td {")
print("border: 1px solid black;")
print("border-collapse: collapse;")
print("padding: 15px;")
print("}")
print("a:link {")
print("color: black;")
print("background-color: transparent;")
print("text-decoration: none;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<h1><hr><center>Link</center></hr></h1>")
print("<hr></hr>")
print("<div></div>")
print("<center><a href='0999847695359.py'>Home</a></center>")
print("<table style='width:100%'>")
print("<tr>")
print("  <th><h4><a href='discom.py'>disconnect</a></h4></th>")
print("  <th><h4><a href='0999847695359.py'>Home</a></h4></th>")
print("  <th><h4><a href='shop0999847695.py'>This Page</a></h4></th>")
print("</tr>")
print("</table>")
print("<hr></hr>")
print("<table style='width:100%'>")
print("<tr>")
print("  <th><h4><a href='about.py'>About</a></h4></th>")
print("  <th><h4><a href='mailto:duopeng@gmail.com'>Contact</a></h4></th>")
print("  <th><h4><a href='not.py'>Link no.6</a></h4></th>")
print(" </tr>")
print("</table>")
print("<hr></hr>")
print("<p><center><a href='not.py'>Show More</a></center></p>")
print("<h6><center><hr>(c) Copyright Website <a href='discom.py'>Disconnect</a></hr></center></h6>")
print("<hr></hr>")
print("<a href='water_PIXEL_normal.png download>")
print("</body>")
print("</html>")

