
#!/usr/bin/python3

print("Content-type: text/html\n\n");
print("<html>")
print("<body>")
print("<head>")
print("<title>Sign up</title>")
print("<style>")
print("body {")
print("background-color: #0088cc;")
print("}")
print("input {")
print("background-color: #006699;")
print("color: White;")
print("}")
print("h1 {")
print("font-family: tohama, arial, sans-serif;")
print("color: White;")
print("}")
print("h6 {")
print("color: White;")
print("}")
print("a:link {")
print("color: White;")
print("background-color: transparent;")
print("text-decoration: none;")
print("}")
print("</style>")
print("<h1><center><hr>Complete imformation</hr></center></h1>")
print("<hr></hr>")
print("<div id='google_t'></div>")
print("<script type='text/javascript'>")
print("function googleTranslateElementInit() {")
print("  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');")
print("}")
print("</script>")
print("")
print("<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>")
print("<form method='POST' action='0999847695359.py'>")
print("<h4><center>First Name : <input type='text' name='fname' value='Cari' required></center></h4>")
print("<h4><center>username : <input type='text' name='username' value='MyUsername' required></center></h4>")
print("<h4><center>Password : <input type='password' name='password' value='Pc@!@#$#@#$%^&*(*&^%*'( required></center></h4>")
print("<h4><center>Comfirm Password : <input type='password' name='comfirmpass'value='----' required> </center></h4>")
print("<h4><center>Address : <input type='text' name='addres' value='0000 street' required></center></h4>")
print("<h4><center>Cookies Policy : <input type='checkbox' name='policy'required></center></h4>")
print("<h4><center>Phone : <input type='tel' value='123 456 7890' required></center></h4>")
print("<h4><center>Email : <input type='email' value='example@example.com' required></center></h4>")
print("<h4><center><input type='submit' name='fin' action='0999847695359.py'></center></h4>")
print("</form>")
print("<h6><center><hr>(c) website <a href='login.py'>Disconnect</a><center></hr><h6>")
print("<hr></hr>")
print("</head>")
print("</body>")
print("</html>")
