#!/usr/bin/python3

print("Content-type: text/html\n\n");
for x in range(100):

    print("<html>")
    print("<head>")
    print("<style>")
    print("table, th, td {")
    print("border: 5px solid;")
    print("border-collapse: collapse;")
    print("border-color: Black;")
    print("}")
    print("th, td {")
    print("padding: 10px;")
    print("user-align: center;")
    print("}")
    print("td {")
    print("background-color: yellow;")
    print("}")
    print("th {")
    print("background-color: gray;")
    print("}")
    print("a:link {")
    print("color: Black;")
    print("background-color: transparent;")
    print(": none")
    print("}")
    print("</style>")
    print("<title>Table</title>")
    print("</head>")
    print("<body>")
    print("")
    print("<table style='width:100%'>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center><a href='https://wdcsx.ca'>Link</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("<tr>")
    print("  <th>user</th>")
    print("  <th>user</th>")
    print("</tr>")
    print("<tr>")
    print("  <td><center>user</center></td>")
    print("  <td><center>user</center></td>")
    print("</tr>")
    print("</table>")
    print("</body>")
    print("</html>")

